### ISSUE TITLE
FW Softlock

### ISSUE THREAD

**Issue by piano-master** [LagoLunatic/wwrando#1]
The game softlocked during the defeated Kalle Demos cutscene.  I did NOT use Light Arrows, but I did kill Kalle Demos with fully charged Master Sword quickspins (maybe this is similar to Molgera softlock?).

Image:
![fw_softlock](https://user-images.githubusercontent.com/6690291/42395033-45bf2c5c-812a-11e8-8b26-a02d34195212.PNG)

Permalink:
MS4wLjAAQWxsRmlkZGxpbmdEYXVnaHRlcgD//x8AAA==

**Comment by LagoLunatic** [comment]
Can you post the permalink too?

**Comment by piano-master** [comment]
Just added it

**Comment by LagoLunatic** [comment]
I tried it on a fresh save and didn't get softlocked.

Did you fight kalle demos more than once and get the softlock every time? Or did this only happen the first time and it worked after that?

**Comment by piano-master** [comment]
I only fought Kalle Demos once and got the softlock.  I can try doing the fight again to see if I softlock again.

**Comment by piano-master** [comment]
I did the fight again and did not softlock. The only difference between the two fights is I messed up doing quickspins on the fight that did not softlock.

**Comment by piano-master** [comment]
I did the fight a third time with good quickspins and did not get the softlock.

**Comment by LagoLunatic** [comment]
I tried it a bunch too and haven't managed to get it once. If it's just a fluke and isn't reproducible there's not much I can do.

For the record what are you playing it on? Console, or which version of dolphin?

**Comment by piano-master** [comment]
Dolphin 5.0-8343

**Comment by LagoLunatic** [comment]
Apparently this is a vanilla softlock, it just has an extremely low chance of happening.
I just removed the cutscene entirely since it's not necessary.
