### ISSUE TITLE
Suggestion Randomize Playable Character's Colours

### ISSUE THREAD

**Issue by Grip555** [LagoLunatic/wwrando#102]
I like having random colours for the characters I make, but It's a pain there's no way to randomize the colours automatically or even a way to save the colour scheme you used last time.

**Comment by durcij** [comment]
Are you suggesting that a change is made to allow for the textures' images to be edited and colorshifted before playing, or are you suggesting multiple texture colors are implemented with random changes to them?

**Comment by Grip555** [comment]
I want the randomizer to remember which colours I used last time, as it can be a pain to get the exact same colours for a new seed, especially when you swap between Casual and non-Casual clothes.

**Comment by LagoLunatic** [comment]
Randomizing player colors implemented in 1.7.0
