### ISSUE TITLE
Softlock upon exiting Fire Mountain with randomized secret caves

### ISSUE THREAD

**Issue by RandomNumbersGuy** [LagoLunatic/wwrando#104]
From what I understand this is a vanilla bug that can be replicated by loading saves, but it's especially frustrating to get stuck from just exiting a cave. A fix would be greatly appreciated, thanks. https://gyazo.com/60f5577a706822609efaa2d6839c3029

**Comment by JarheadHME** [comment]
81d059423076f6da92cfee9dd38121115a44b97b

**Comment by RandomNumbersGuy** [comment]
Thanks fam

**Comment by AdamALittle** [comment]
I'm still having this same issue, but while exiting Tower of the Gods with entry from Fire Mountain. I am randomizing Dungeons and Secret Caves (Together)

**Comment by LagoLunatic** [comment]
@AdamALittle I tried exiting TotG connected to fire mountain's entrance and didn't get the softlock. So you're likely on v1.5.0, which is outdated. Update to v1.5.1.

**Comment by OlafurKrH** [comment]
im on v1.5.1 and this just happened to me.

**Comment by LagoLunatic** [comment]
Post your permalink.

**Comment by OlafurKrH** [comment]
MS41LjEAQUdpYW50Q29jawD//z8EHwADAQE=

If you see my seed name, I'm very sorry. I have a very dirty sense of humor

**Comment by UncleZeldo** [comment]
It just happened to me too, on version 1.5.1. My permalink is:

MS41LjEAQWxsQnV0U3Vua2VuVHJlYXN1cmUA/z8/BB4AAwEB

I also made the mistake of saving inside the cave -- now it softlocks as soon as I try to launch the game. Is there any way to fix the save file? Or is it hopeless?

**Comment by state18** [comment]
`Wind Waker Randomizer Version 1.5.1
Permalink: MS41LjEAV2VzdGVybHlDb21wbGltZW50YXJ5R29oZGFuAA8FAwQeAAIAAQ==`

It happened to me too. I was coming out of the Wind Temple (with an entrance/exit through Fire Mountain). I was hoping the loop may end with a game over but it didn't happen after 20 minutes.
