### ISSUE TITLE
DRC BK Logic Problem

### ISSUE THREAD

**Issue by Redstore97** [LagoLunatic/wwrando#107]
Hey there,

Great Job on the Randomizer! I totaly love it.

Well here is a little Issue I got on my last game.
Permalink: MS41LjEAUmV0aXJpbmdIZWFydGZlbHRBbmtsZQD/vz8AHgACAAE=

The Dragon Roost Cavern Big Key was in the Letter from Komali's Father. (I checked the Spoiler-Log)
However as far as I know, you don't get this Letter unless you have beaten Gohma. So there was no way for me to get this Key and to beat him.
![drc big key](https://user-images.githubusercontent.com/47308679/52185674-2f5af500-2822-11e9-93a7-e636e4bef65b.PNG)

**Comment by LagoLunatic** [comment]
You get that letter after you own Farore's Pearl. In the vanilla game this means after you beat Kalle Demos, but in randomizer you can get Farore's Pearl from anywhere and it'll trigger the letter.
