### ISSUE TITLE
Options Switched?

### ISSUE THREAD

**Issue by Grip555** [LagoLunatic/wwrando#109]
When I selected randomized sword and randomized dungeon entrances, instead I was swordless and had random cave entrances.

**Comment by LagoLunatic** [comment]
Post your permalink.

**Comment by Grip555** [comment]
MS41LjEARmlzaHlGaXNoeUlzU29Tb0dvb2QAf88rARwAAwEB

**Comment by LagoLunatic** [comment]
Nope, there are swords placed and cave entrances lead to their original caves.

You must have made multiple ISOs with different settings and then mistakenly booted up the wrong ISO.

**Comment by Grip555** [comment]
But I selected randomized dungeon entrances, yet they were in their normal areas and I wanted to start with a random sword, not no sword.

**Comment by LagoLunatic** [comment]
Only DRC and WT are in their normal entrances. ET FW and TotG are in different entrances. There's only 5 dungeons, so it's very common for one or two to be in vanilla locations.

"Randomized sword" doesn't mean you start with a random sword. It means you start with no sword and have to find it in a random location.
"Swordless" means not only do you not start with a sword, but you can never find one either.
