### ISSUE TITLE
Suggestion: spoils log

### ISSUE THREAD

**Issue by christopher842** [LagoLunatic/wwrando#110]
I think that it would be a great idea if the spoiler log tells you what item each treasure chart contains

**Comment by LagoLunatic** [comment]
It does already, scroll down

**Comment by christopher842** [comment]
Not for me. Here's an example of what it says
Sunken Treasure:                                     Magic Meter Upgrade
It's not telling me which sunken treasure/treasure chart it is

**Comment by LagoLunatic** [comment]
```
Pawprint Isle:
    Sunken Treasure:                                     Silver Rupee
```

```
  Treasure Chart 30: Pawprint Isle
```

Means that treasure chart 30 gets you a silver rupee.

**Comment by christopher842** [comment]
[WW Random OutgoingWhatsoeverRitoNew - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/2872334/WW.Random.OutgoingWhatsoeverRitoNew.-.Spoiler.Log.txt)

![screenshot_2019-02-16-15-03-09](https://user-images.githubusercontent.com/47699924/52904591-14ae5600-31fc-11e9-8650-1348542c7e90.png)

Here is my spoiler log it doesn't say something like that

**Comment by LagoLunatic** [comment]
Yes, in fact it does say something like that. Like I said in my first comment: scroll down.

**Comment by christopher842** [comment]
It only says what item the treasure chart contains for some of them but not for all
Is the magic meter upgrade considered a progression item?

**Comment by LagoLunatic** [comment]
Nope, it says it for all items regardless of whether they're progress or not.
Magic meter upgrade is sometimes a progress item, sometimes not, depending on your settings.

**Comment by christopher842** [comment]
![screenshot_2019-02-16-15-17-36](https://user-images.githubusercontent.com/47699924/52904738-40324000-31fe-11e9-9e94-37253ed09288.png)
Here are all of the options that I checked off. Treasure charts wasn't one of the selected options but the magic meter upgrade is in one of the charts. Does this mean that my seed doesn't really require it?

**Comment by LagoLunatic** [comment]
Nothing in your seed requires the meter upgrade, yes. It's only useful for the flight control platform minigame and swordless mode as far as I can remember.

**Comment by christopher842** [comment]
Well thank you for the information. I appreciate it. I actually got a good seed on my opinion because I was able to purchase the master sword from beedle's shop for 20 rupees which was really convenient.
