### ISSUE TITLE
Change model without randomize

### ISSUE THREAD

**Issue by Sleora** [LagoLunatic/wwrando#111]
Hello, I'm looking for a way to change the appearance of my character but randomize the game. Only, when I use WWRandomizer, I can only change my character if I randomize the game. So I would like to know if there is a way to change the character's appearance by starting the game from the beginning.

P.S: I tried to extract the iso and replace the Link.arc file but there was no way to reinject the modified file into the iso.

**Comment by Sleora** [comment]
*whitout randomizing the game.

**Comment by LagoLunatic** [comment]
>P.S: I tried to extract the iso and replace the Link.arc file but there was no way to reinject the modified file into the iso.

Should be doable with this program https://www.romhacking.net/utilities/619/
