### ISSUE TITLE
Slight logic issue with Knight's Crests

### ISSUE THREAD

**Issue by emerald000** [LagoLunatic/wwrando#116]
One of the locations you can farm Knight's Crests is in Savage Labyrinth floor 27. Currently, the logic checks for accessibility of the chest on floor 30. This adds two extra checks that aren't required to get the Knight's Crests: that you can defeat Darknuts (there are droppable weapons on floor 27), and that you can play Wind's Requiem.

**Comment by LagoLunatic** [comment]
I forgot about the floor 27 ones not having requirements to kill. But I wonder if I should remove that requirement - there's only a single darknut on floor 27 and you need to go down 27 floors to get it. That seems far more annoying than going down 30 floors to get 3 knight's crests (which was already annoying).
