### ISSUE TITLE
[Suggestion] Scrollable checklist for choosing all locations individually

### ISSUE THREAD

**Issue by Compynerd255** [LagoLunatic/wwrando#119]
A few past changes have had to do with separating quests into more categories. While the categories are nice as a quick suggestion feature, I think it would ultimately be more powerful to be able to go through the entire list of locations and enable/disable individual items beyond what the categories normally do (e.g. enable the chest in Mother and Child Isles without also enabling other overworld chests). The categories could still be available, perhaps as an "all/none/some" parent checkbox, and being able to see individual changes would also make it clearer what each of the individual categories represent (as well as being able to have less of them).

**Comment by LagoLunatic** [comment]
I don't like this idea. I think this is too much choice, there's no need to be able to deselect most of the individual locations. Also, this would add like 300 options and make the permalink super long.

**Comment by Compynerd255** [comment]
Sure, but I don't imagine you'd be fiddling around with the details list most of the time - you'd do most of your selections through categories and maybe tweak one or two settings, such as turning the Combat Secret Caves on but turning off Savage Labyrinth. You could also potentially compress the permalink (perhaps using RLE and arranging locations that are likely to be turned on or off together to be next to each other), though I really don't see why permalink length is an issue, since it's usually shared via select all/copy/paste anyway.
