### ISSUE TITLE
[Suggestion] Customizer! like the ALTTP Customizer.

### ISSUE THREAD

**Issue by FatBoySlim2000** [LagoLunatic/wwrando#130]
The Link to the Past randomizer has a customizer where you get to place items wherever you want. I think it would be awesome if the same thing was done for this randomizer. I would personally take the time to place every item wherever I want. Plus I'd make the seed for a friend.

**Comment by LagoLunatic** [comment]
There's a fork that allows for that, although it's months outdated by now: https://github.com/andirigible/wwplando

I'm not planning to add this feature.
