### ISSUE TITLE
Bug - Impossible seed

### ISSUE THREAD

**Issue by oskar3123** [LagoLunatic/wwrando#131]
Version: 1.6.0
Permalink: `MS42LjAAU2xpbXlSZWxhdGVkU3RhbGZvcwAHAQMABxAgAAAAAAAA`
Spoiler Log: https://gist.github.com/oskar3123/d99c8b23fceb4b71101d9902405e7af8

I'm pretty sure I've encountered an impossible seed since according to the spoiler log I have to get a Triforce shard from DRC but I cannot access any more but the first three chests in the dungeon because it did not give me enough small keys.

It is entirely possible that I'm just missing something obvious since I'm pretty new at the randomizer.

**Comment by LagoLunatic** [comment]
Ice arrows freeze lava. https://imgur.com/R0cYujl

**Comment by oskar3123** [comment]
Aah, I feel so dumb right now. Thanks for the snappy response.
