### ISSUE TITLE
[Bug?] Dins pearl in master sword chamber

### ISSUE THREAD

**Issue by slader007** [LagoLunatic/wwrando#134]
Wind Waker Randomizer Version 1.6.0
Permalink: MS42LjAAVW5kZWFkVW5oYXJtZWREYXBobmVzAAcBAwAHECAAAAAAAAA=
Seed: UndeadUnharmedDaphnes

I don't know if this is unbeatable or if I am just missing something but the spoiler log says that dins pearl is in the Master Sword Chamber. If I'm not mistaken you need all of the pearls to get into the ToTG and hyrule.

**Comment by LagoLunatic** [comment]
>If I'm not mistaken you need all of the pearls to get into the ToTG

Correct.

>and hyrule.

Nope, just need the full triforce.

**Comment by slader007** [comment]
> > If I'm not mistaken you need all of the pearls to get into the ToTG
> 
> Correct.
> 
> > and hyrule.
> 
> Nope, just need the full triforce.

Oh I didn't realize that. Thank you for the very fast reply
