### ISSUE TITLE
Chest Won't Spawn / I can't continue

### ISSUE THREAD

**Issue by ImJittery** [LagoLunatic/wwrando#138]
Permalink : MS42LjAAWmVicmFHcmF5UGlua1BpenphQ2Fub2UAH1M7wQdYAEAgAAAAAA==
Version: 1.6.0
I'm using official hardware.
I went to Birds Peak Rock Secret Cave (Which Got Randomized To Shark Island Secret Cave), and killed all the enemy's, but the chest won't spawn. I've re-done it twice. The chest is supposed to have the Iron Boots, which I need to progress. I'm going to attach the Spoiler/Non-Spoiler logs.

[WW Random ZebraGrayPinkPizzaCanoe - Non-Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/3196028/WW.Random.ZebraGrayPinkPizzaCanoe.-.Non-Spoiler.Log.txt)
[WW Random ZebraGrayPinkPizzaCanoe - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/3196029/WW.Random.ZebraGrayPinkPizzaCanoe.-.Spoiler.Log.txt)

**Comment by JarheadHME** [comment]
It's something on your end, cause I just did it and the chest spawned fine. You might have gotten unlucky twice and a miniblin or something clipped out of bounds and never counted as being killed.

**Comment by wooferzfg** [comment]
I've had this happen before, and I think it's a vanilla bug that happens kinda randomly.

**Comment by ImJittery** [comment]
I see.... Thank, both of, you. I'll try it again and see if it works. Again, thank you!

**Comment by ImJittery** [comment]
Ok, so I did it a third time, and it worked! Sorry for wasting anyone's time, and thank you guys for helping me!
