### ISSUE TITLE
I have all 3 Pearls and completed TotG but the entrance to Hyrule isn't there.

### ISSUE THREAD

**Issue by GarthStevens5** [LagoLunatic/wwrando#139]
Like the title says, I have all 3 pearls and completed the Tower of the Gods, but the yellow ring portal to descend into Hyrule isn't outside the TotG entrance. Am I missing something? 

Seed Name: BurlyTaciturnJan
Permalink: MS42LjBfMWNiZWQ0YwBCdXJseVRhY2l0dXJuSmFuABcNAwAHECAAAAAAAAA=
[WW Random BurlyTaciturnJan - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/3243507/WW.Random.BurlyTaciturnJan.-.Spoiler.Log.txt)

**Comment by wooferzfg** [comment]
The only requirement for entering Hyrule is having all the Triforce shards.
