### ISSUE TITLE
Light Arrows Glitch Jalhalla

### ISSUE THREAD

**Issue by XerShade** [LagoLunatic/wwrando#14]
So tiny little glitch is when you kill the poes during the Jalhalla fight with light arrows the game will hang for a bit when he reforms and the poes will not actually be defeated, his health bar does not actually go down when they are killed like this.

Possible fix would be making the poes immune to light arrows, or checking for the flags that lower his hp. I have a video clip of the fight here from my stream: https://www.twitch.tv/videos/289715360

**Comment by LagoLunatic** [comment]
Known issue, this can't actually softlock the game unlike stalfos so I won't make poes immune to light arrows. Especially since that would affect poes outside the jalhalla fight too.

**Comment by XerShade** [comment]
Is there no way to change his hp with the light arrows animation? It appears the flag that lowers his hp is tied to the poes entering the normal death animation, obviously when the light arrows are used this doesn't happen.

**Comment by LagoLunatic** [comment]
It would involve adding new code to the poe's light arrow death code that registers their death with jalhalla properly. Strangely, the original devs *already* coded that - so in theory it should work. I don't know why it doesn't. I'm sure it's technically possible to fix *somehow* but figuring out how specifically would be very very time consuming.

Stalfos are a bigger priority anyway, I'd rather figure out how to do a proper fix to stalfos first. If I do ever figure that out maybe I'll look into poes too but I dunno.

**Comment by XerShade** [comment]
Is it any Stalfos that bug when you use light arrows or just the ones in earth temple?

**Comment by LagoLunatic** [comment]
It's all of them, but the only times it matters are when you can't progress until all enemies in the room are dead. Which I think is just earth temple and savage labyrinth. Savage is especially bad since you can easily lose 25+ minutes of progress to it.

**Comment by XerShade** [comment]
Yeah if possible I'd look at a way to have light arrows trigger the "normal death" code, that seems to be the issue with the poes and stalfos. It would fix both.

**Comment by LagoLunatic** [comment]
It's not as simple as using the normal death code, since each different way each enemy can die has different code. And using the wrong code would make it use the wrong death animation. I would basically need to read through the death code that works correctly to understand all of it, and re-implement it in a custom function that gets run for light arrow death.
