### ISSUE TITLE
[Issue] Possible soft-lock?

### ISSUE THREAD

**Issue by ronrick420** [LagoLunatic/wwrando#146]
MS42LjAASW1wdWxzaXZlVm9sY2FuaWNSb29tAAcBAwAHECAAAAAAAAA=
Spoiler Log: https://pastebin.com/qXbyisqz
I am unable to get into the tower of the gods.
My problem is my bait bag is in the master sword chamber. And you need the bait bag to get onto the top of headstone island where my hookshot is. and you need the hookshot to get onto diamond steppe island and Farore's Pearl is inside of the warp maze.

**Comment by LagoLunatic** [comment]
The master sword chamber is in hyrule, not TotG. All you need is 8 triforce shards to reach it, no pearls.

**Comment by wooferzfg** [comment]
You can get to the Master Sword Chamber when you get all the Triforce shards.

**Comment by ronrick420** [comment]
Alright thanks for the quick response.
