### ISSUE TITLE
[Suggestion] "All Dungeons Mode"

### ISSUE THREAD

**Issue by XerShade** [LagoLunatic/wwrando#15]
So I was wondering if it would be possible to make an "all dungeons" mode by making it so at least six of the triforce shards are held by the six great sea bosses, and either the player starts with the remaining piece, it's put on the ghost ship, or it is randomized.

Could probably make it a cool name like "Courage Mode" or something too.

**Comment by Algernonab** [comment]
I would like to amend this by suggesting that one of the remaining Triforce Shards be put on Floor 50 of the Savage Labyrinth.

**Comment by MegaKBang** [comment]
Why not change it into an option that requires the player to achieve certain goals which will reward you with a triforce shard?

**Comment by LagoLunatic** [comment]
Race Mode seems close enough to this. It puts required items such as triforce shards on 4 of the 6 dungeons bosses.
