### ISSUE TITLE
Beedle not appearing on Windfall

### ISSUE THREAD

**Issue by Wiimeiser** [LagoLunatic/wwrando#152]
Not sure if this was fixed in 1.6.1, but in 1.6.0 Beedle's shop ship fails to spawn on Windfall Island during the day. Strangely, it's only on Windfall Island during the day, not on any other island. I don't know what's happening here, I could hazard a guess, but I'd most likely be wrong...

**Comment by LagoLunatic** [comment]
Windfall beedle is nighttime specific, this is from vanilla

**Comment by wooferzfg** [comment]
Beedle only appears at night on Windfall in the original game.

**Comment by Wiimeiser** [comment]
So him appearing before was the bug, I'm guessing?

**Comment by LagoLunatic** [comment]
Beedle has never appeared at windfall during the day. You must be thinking of another island.
