### ISSUE TITLE
[Bug]Uncompletable seed 

### ISSUE THREAD

**Issue by Cymnoi** [LagoLunatic/wwrando#155]
So about 4 hours into this run i was keeping track of all the areas that it was possible for me to do without glitches since I don't know how to do many of them very well. And ran into an issue where i ran out of places to check so i double checked my list and tried even the places i figured i wouldn't be able to do hoping i would somehow manage to get somewhere eventually i gave up and consulted the spoiler log only to find that the bait bag that i needed to progress was locked behind phantom Gannon in the forsaken fortress on a swordless run I've tried before so I know that the only phantom Gannon the light arrows can kill is the one in hyrule but i decided to check where the final bow upgrade was which was in the tower of gods which i needed dins pearl which was in the earth temple to get now normally this wouldn't be a problem but the mirror shield to get anywhere near where that chest was wasn't in the forbidden woods which I needed the deku leaf to reach and the deku leaf was conveniently locked behind the bait bag so even if light arrows could kill that phantom gannon it was impossible for me to get them to do so without having the item locked behind him. Long story short the deku leaf was locked behind the bait bag and the bait bag was impossible for me to obtain because i was on a swordless seed If you want to go through and confirm this yourself I've attached the spoiler log
[WW Random FuttSluckingButs - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/3705635/WW.Random.FuttSluckingButs.-.Spoiler.Log.txt)

**Comment by LagoLunatic** [comment]
>the bait bag that i needed to progress was locked behind phantom Gannon in the forsaken fortress on a swordless run

On swordless mode, Phantom Ganon is made vulnerable to the hammer instead of the sword. Hammer is accessible in your seed so there's no issue.

Also you should format your posts better. A giant wall of text with no punctuation in it is borderline impossible to read.
