### ISSUE TITLE
[BUG] Can't complete my seed

### ISSUE THREAD

**Issue by Axodique** [LagoLunatic/wwrando#156]
Seed:MS42LjEAU2F2YWdlQW5jaWVudEdyYW5kbW90aGVyABcNS4AHECAAAAAAAAA=

Tracker: https://www.wooferzfg.me/tww-rando-tracker/tracker.html?f=D1GF1PSC1CSC0SSQ0LSQ0ST0MG0FG1MAI0PR0SUB0ERC0BOG0TRI0TRE0EP1MIS1TIN0KL0REN0RCH0SWO0SRB1STS0RM0SAV0BSM0&g=0&p=1&v=1.6.1&c=1

Sorry if i am annoying but i can't seem to complete this seed, i have checked every location avaible to me but i don't find anything to help me progress. thanks!

**Comment by LagoLunatic** [comment]
What items have you found?  You need to specify how far you've gotten or I don't know what part you can't figure out.

**Comment by Axodique** [comment]
I put the tracker, i'm pretty sure i've marked everyting right.

**Comment by Axodique** [comment]
And i've uploaded my dolphin save if you want: https://mega.nz/#!CA5VCabJ!z7RW52N7fiKFYzAbt2hEo3QfSQ58FQpPd8xa81dGFMw

**Comment by wooferzfg** [comment]
That tracker link won't show your progress because it's only saved locally by default. You should instead click "Export Progress" and send the downloaded file.

**Comment by Axodique** [comment]
oh sorry, here you go: https://mega.nz/#!aM4RFCDJ!6EIPxcIivXAqMpqg32Y6Zj0CCnYWRwLa5l1MZRts5yA

**Comment by LagoLunatic** [comment]
You have all 3 pearls so you should be able to go to the TotG entrance to go in DRC and get some items you need.

**Comment by Axodique** [comment]
Oh right! I kinda forgot i shuffled the dungeons for a bit.. sorry for the inconvinience.
