### ISSUE TITLE
Download link timing out

### ISSUE THREAD

**Issue by VanillaDracula** [LagoLunatic/wwrando#157]
For some reason i am unable to download using the link. I get a generic timeout message when i try to download.

**Comment by LagoLunatic** [comment]
It works for me. Is this the link you're downloading from?
https://github.com/LagoLunatic/wwrando/releases/download/1.6.1/Wind_Waker_Randomizer_1.6.1_64bit.zip

**Comment by VanillaDracula** [comment]
Yeah it is, it must be something with my isp, I did end up getting my buddy
to grab me the download and send it to me. I'll try it again when it
updates and then tell at my isp. I appreciate you reaching out!

Have a good night!
