### ISSUE TITLE
Black screen on launch

### ISSUE THREAD

**Issue by der-siebte-schatten** [LagoLunatic/wwrando#158]
Hello there

Using the last development version of Dolphin (currently 5.0-11160), I can't boot up the randomized game. After the Nintendo and Dolby Digital logos, screen just stays black forever, no responses to inputs.

The original ISO seems fine. It works correctly and the MD5 hash corresponds.

Any clue to this?

**Comment by LagoLunatic** [comment]
Upload your spoiler log

**Comment by der-siebte-schatten** [comment]
So a quick update, because some happened on Discord and on the Dolphin Forums.

LagoLunatic tried my seeds and they worked for him, they also worked on my Android phone. I don't use custom Link models, so that's a possibility out also…

Later, someone on the forums told me to try in portable mode (by creating a portable.txt file in the Dolphin folder), and there, it works! By restablishing all my settings in portable mode, the issue came back, so something in my configuration might be the solution…

Brb after some tests...

**Comment by der-siebte-schatten** [comment]
WELP! Found the issue, it's the GameCube main menu (the IPL). If not skipped, the game does not boot… So a stupid thing… X)

You can add that in your guide maybe, I'm closing the issue now that it works...
