### ISSUE TITLE
[BUG] Spoiler Log Logic Issue with Big Key

### ISSUE THREAD

**Issue by SirJubs** [LagoLunatic/wwrando#159]
First of all thanks for all the hard work, I'm loving the randomizer!
During my run (permalink: MS42LjFfTk9HSVQAQ29ycmVjdEFubnVhbEZsZWV0ABcAEAAHMCABAAAAAAA=
With Seed: CorrectAnnualFleet)

on V 1.6.1 the logic engine seems to be trying to add things to the spoiler log progression that aren't required specifically the big keys of dungeons. If you look at wind temple in the spoiler log, for instance, it says to go to Wind temple and collect the WT big key, but that item is not required to complete the run as the boss item from wind temple is not required to beat the game (Earth temple has the same issue as well within this seed and [settings).](url)

Nothing really serious here, but these issues point out some possible issues with how the randomizer is determining logic. 

Thanks for all the hard work!

Posted below is the spoiler log:

Wind Waker Randomizer Version 1.6.1_NOGIT
Permalink: MS42LjFfTk9HSVQAQ29ycmVjdEFubnVhbEZsZWV0ABcAEAAHMCABAAAAAAA=
Seed: CorrectAnnualFleet
Options selected:
  progression_dungeons, progression_great_fairies, progression_puzzle_secret_caves, progression_short_sidequests, progression_savage_labyrinth, randomize_entrances: Disabled, swift_sail, instant_text_boxes, reveal_full_sea_chart, num_starting_triforce_shards: 0, generate_spoiler_log, sword_mode: Randomized Sword, skip_rematch_bosses, disable_tingle_chests_with_tingle_bombs, custom_player_model: Link, custom_colors: OrderedDict([('Shirt', [0, 85, 255]), ('Undershirt', [170, 255, 255])])

Playthrough:
1:
  Windfall Island:
      Ivan - Catch Killer Bees:              Delivery Bag
      Mrs. Marie - Catch Killer Bees:        Boomerang
  Dragon Roost Cavern:
      Rat Room:                              Triforce Shard 5
      Rat Room Boarded Up Chest:             DRC Big Key
  Northern Fairy Island:
      Great Fairy:                           Deku Leaf
2:
  Dragon Roost Cavern:
      Pot Room Chest:                        Grappling Hook
      Mini-Boss:                             Command Melody
  Cliff Plateau Isles:
      Cave:                                  Din's Pearl
      Highest Isle:                          Progressive Picto Box
3:
  Windfall Island:
      Lenzo's House - Left Chest:            Cabana Deed
      Lenzo's House - Right Chest:           Progressive Sword
      Pompie and Vera:                       Moblin's Letter
  Dragon Roost Cavern:
      Gohma Heart Container:                 Triforce Shard 1
  Forbidden Woods:
      Inside Hollow Tree's Mouth:            Triforce Shard 3
      Climb to Top Using Boko Baba Bulbs:    Triforce Shard 4
      Tall Room Before Mini-Boss:            Bait Bag
      Chest in Locked Tree Trunk:            FW Big Key
  Pawprint Isle:
      Chuchu Cave - Scale the Wall:          Farore's Pearl
4:
  Windfall Island:
      Maggie - Reward:                       Iron Boots
  Forbidden Woods:
      Mothula Mini-Boss Room:                Wind God's Aria
      Kalle Demos Heart Container:           Progressive Picto Box
  Bird's Peak Rock:
      Cave:                                  Power Bracelets
5:
  Pawprint Isle:
      Chuchu Cave - Behind First Boulder:    Magic Meter Upgrade
  Outset Island:
      Savage Labyrinth - Floor 30:           Bombs
  Eastern Fairy Island:
      Great Fairy:                           Progressive Bow
  Bomb Island:
      Cave:                                  Nayru's Pearl
6:
  Tower of the Gods:
      Hop Across Floating Boxes:             Mirror Shield
      Second Chest Guarded by Armos Knights: TotG Big Key
  Southern Fairy Island:
      Great Fairy:                           Skull Hammer
7:
  Tower of the Gods:
      Gohdan Heart Container:                Progressive Sword
  Forsaken Fortress:
      Chest Inside Lower Jail Cell:          Progressive Sword
  Wind Temple:
      Chest at Top of Hub Room:              WT Big Key
  Angular Isles:
      Cave:                                  Maggie's Letter
8:
  Windfall Island:
      Cafe Bar - Postman:                    Earth God's Lyric
9:
  Earth Temple:
      Kill All Floormasters in Foggy Room:   Hookshot
10:
  Diamond Steppe Island:
      Warp Maze Cave - First Chest:          Progressive Bow
      Warp Maze Cave - Second Chest:         Triforce Shard 2
11:
  Windfall Island:
      Kreeb:                                 Triforce Shard 8
      Transparent Chest:                     Progressive Bow
  Earth Temple:
      Stalfos Mini-Boss Room:                ET Big Key
  Fire Mountain:
      Cave - Chest:                          Progressive Sword
  Ice Ring Isle:
      Cave - Chest:                          Triforce Shard 6
  Needle Rock Isle:
      Cave:                                  Triforce Shard 7
12:
  Ganon's Tower:
      Rooftop:                               Defeat Ganondorf

All item locations:
Outset Island:
    Underneath Link's House:                             Piece of Heart
    Mesa the Grasscutter's House:                        Piece of Heart
    Orca - Give 10 Knight's Crests:                      Purple Rupee
    Orca - Hit 500 Times:                                Forbidden Tingle Statue
    Great Fairy:                                         Platform Chart
    Jabun's Cave:                                        Hero's Charm
    Dig up Black Soil:                                   Boko Baba Seed
    Savage Labyrinth - Floor 30:                         Bombs
    Savage Labyrinth - Floor 50:                         Purple Rupee
    Sunken Treasure:                                     Orange Rupee
Windfall Island:
    Jail - Tingle - First Gift:                          Piece of Heart
    Jail - Tingle - Second Gift:                         Piece of Heart
    Jail - Maze Chest:                                   Treasure Chart 7
    Chu Jelly Juice Shop - Give 15 Green Chu Jelly:      Joy Pendant
    Chu Jelly Juice Shop - Give 15 Blue Chu Jelly:       Heart Container
    Ivan - Catch Killer Bees:                            Delivery Bag
    Mrs. Marie - Catch Killer Bees:                      Boomerang
    Mrs. Marie - Give 1 Joy Pendant:                     Treasure Chart 32
    Mrs. Marie - Give 21 Joy Pendants:                   Treasure Chart 38
    Mrs. Marie - Give 40 Joy Pendants:                   Great Fairy Chart
    Lenzo's House - Left Chest:                          Cabana Deed
    Lenzo's House - Right Chest:                         Progressive Sword
    Lenzo's House - Become Lenzo's Assistant:            Orange Rupee
    Lenzo's House - Bring Forest Firefly:                Skull Necklace
    House of Wealth Chest:                               Piece of Heart
    Maggie's Father - Give 20 Skull Necklaces:           Blue Rupee
    Maggie - Letter:                                     Heart Container
    Maggie - Reward:                                     Iron Boots
    Cafe Bar - Postman:                                  Earth God's Lyric
    Kreeb:                                               Triforce Shard 8
    Transparent Chest:                                   Progressive Bow
    Tott:                                                Knight's Crest
    Pirate Ship:                                         Golden Feather
    40 Rupee Auction:                                    Joy Pendant
    5 Rupee Auction:                                     Red Rupee
    60 Rupee Auction:                                    Piece of Heart
    80 Rupee Auction:                                    Orange Rupee
    Zunari - Stock Exotic Flower in Zunari's Shop:       Treasure Chart 28
    Sam - Decorate the Town:                             Heart Container
    Mila:                                                Piece of Heart
    Battlesquid - First Prize:                           Silver Rupee
    Battlesquid - Second Prize:                          Triforce Chart 5
    Battlesquid - Under 20 Shots Prize:                  Golden Feather
    Pompie and Vera:                                     Moblin's Letter
    Kamo:                                                Magic Armor
    Minenco:                                             Piece of Heart
    Linda and Anton:                                     Golden Feather
    Sunken Treasure:                                     Silver Rupee
Dragon Roost Island:
    Wind Shrine:                                         Piece of Heart
    Rito Aerie - Give Hoskit 20 Golden Feathers:         Treasure Chart 14
    Chest on Top of Boulder:                             Piece of Heart
    Fly Across Platforms Around Island:                  Skull Necklace
    Rito Aerie - Baito:                                  Piece of Heart
    Secret Cave:                                         Triforce Chart 1
    Sunken Treasure:                                     Hyoi Pear
Dragon Roost Cavern:
    First Room:                                          DRC Small Key
    Alcove With Water Jugs:                              DRC Small Key
    Boarded Up Chest:                                    DRC Small Key
    Chest Across Lava Pit:                               DRC Small Key
    Rat Room:                                            Triforce Shard 5
    Rat Room Boarded Up Chest:                           DRC Big Key
    Bird's Nest:                                         Treasure Chart 40
    Dark Room:                                           Purple Rupee
    Tingle Chest in Hub Room:                            Skull Necklace
    Pot Room Chest:                                      Grappling Hook
    Mini-Boss:                                           Command Melody
    Under Rope Bridge:                                   Treasure Chart 16
    Tingle Statue Chest:                                 Treasure Chart 41
    Big Key Chest:                                       DRC Dungeon Map
    Boss Stairs Right Chest:                             DRC Compass
    Boss Stairs Left Chest:                              Purple Rupee
    Gohma Heart Container:                               Triforce Shard 1
Forest Haven:
    On Tree Branch:                                      Treasure Chart 17
    Small Island Chest:                                  Piece of Heart
    Sunken Treasure:                                     Joy Pendant
Forbidden Woods:
    First Room:                                          Piece of Heart
    Inside Hollow Tree's Mouth:                          Triforce Shard 3
    Climb to Top Using Boko Baba Bulbs:                  Triforce Shard 4
    Hole in Tree:                                        Skull Necklace
    Morth Pit:                                           Purple Rupee
    Vine Maze Left Chest:                                Piece of Heart
    Vine Maze Right Chest:                               FW Dungeon Map
    Tall Room Before Mini-Boss:                          Bait Bag
    Mothula Mini-Boss Room:                              Wind God's Aria
    Past Seeds Hanging by Vines:                         Orange Rupee
    Chest Across Red Hanging Flower:                     FW Compass
    Tingle Statue Chest:                                 Telescope
    Chest in Locked Tree Trunk:                          FW Big Key
    Big Key Chest:                                       FW Small Key
    Double Mothula Room:                                 Submarine Chart
    Kalle Demos Heart Container:                         Progressive Picto Box
Greatfish Isle:
    Hidden Chest:                                        Piece of Heart
    Sunken Treasure:                                     Piece of Heart
Tower of the Gods:
    Chest Behind Bombable Walls:                         TotG Small Key
    Hop Across Floating Boxes:                           Mirror Shield
    Light Two Torches:                                   Piece of Heart
    Skulls Room Chest:                                   Knight's Crest
    Shoot Eye Above Skulls Room Chest:                   TotG Small Key
    Tingle Statue Chest:                                 Piece of Heart
    First Chest Guarded by Armos Knights:                TotG Dungeon Map
    Stone Tablet:                                        Purple Rupee
    Darknut Mini-Boss Room:                              Silver Rupee
    Second Chest Guarded by Armos Knights:               TotG Big Key
    Floating Platforms Room:                             Orange Rupee
    Top of Floating Platforms Room:                      Empty Bottle
    Big Key Chest:                                       TotG Compass
    Gohdan Heart Container:                              Progressive Sword
    Sunken Treasure:                                     Purple Rupee
Hyrule:
    Master Sword Chamber:                                Purple Rupee
Forsaken Fortress:
    Phantom Ganon:                                       Piece of Heart
    Chest Outside Upper Jail Cell:                       Red Rupee
    Chest Inside Lower Jail Cell:                        Progressive Sword
    Chest Guarded By Bokoblin:                           FF Compass
    Chest on Bed:                                        FF Dungeon Map
    Helmaroc King Heart Container:                       Silver Rupee
    Sunken Treasure:                                     Red Rupee
Mother and Child Isles:
    Inside Mother Isle:                                  Note to Mom
    Sunken Treasure:                                     Treasure Chart 15
Fire Mountain:
    Cave - Chest:                                        Progressive Sword
    Lookout Platform Chest:                              Treasure Chart 10
    Lookout Platform - Destroy the Cannons:              Orange Rupee
    Big Octo:                                            Earth Tingle Statue
    Sunken Treasure:                                     Treasure Chart 33
Ice Ring Isle:
    Frozen Chest:                                        Progressive Quiver
    Cave - Chest:                                        Triforce Shard 6
    Inner Cave - Chest:                                  Orange Rupee
    Sunken Treasure:                                     Treasure Chart 9
Headstone Island:
    Top of the Island:                                   Silver Rupee
    Submarine:                                           Joy Pendant
    Sunken Treasure:                                     Progressive Bomb Bag
Earth Temple:
    Transparent Chest In Warp Pot Room:                  ET Small Key
    Chest Behind Destructible Walls:                     ET Small Key
    Transparent Chest in First Crypt:                    Orange Rupee
    Chest In Three Blocks Room:                          ET Dungeon Map
    Chest Behind Statues:                                Dragon Tingle Statue
    Casket in Second Crypt:                              Skull Necklace
    Stalfos Mini-Boss Room:                              ET Big Key
    Tingle Statue Chest:                                 Piece of Heart
    End of Foggy Room With Floormasters:                 ET Small Key
    Kill All Floormasters in Foggy Room:                 Hookshot
    Chest in Third Crypt:                                Triforce Chart 6
    Many Mirrors Room Right Chest:                       ET Compass
    Many Mirrors Room Left Chest:                        Hyoi Pear
    Stalfos Crypt Room:                                  Triforce Chart 2
    Big Key Chest:                                       Joy Pendant
    Jalhalla Heart Container:                            Piece of Heart
Wind Temple:
    Chest Between Two Dirt Patches:                      WT Small Key
    Tingle Statue Chest:                                 Piece of Heart
    Chest Behind Stone Head:                             Treasure Chart 27
    Chest in Left Alcove:                                WT Small Key
    Big Key Chest:                                       WT Compass
    Chest In Many Cyclones Room:                         Purple Rupee
    Chest In Middle Of Hub Room:                         Silver Rupee
    Spike Wall Room - First Chest:                       WT Dungeon Map
    Spike Wall Room - Destroy All Cracked Floors:        Golden Feather
    Wizzrobe Mini-Boss Room:                             Piece of Heart
    Chest at Top of Hub Room:                            WT Big Key
    Chest Behind Seven Armos:                            Orange Rupee
    Kill All Enemies in Tall Basement Room:              Rainbow Rupee
    Molgera Heart Container:                             Progressive Wallet
Ganon's Tower:
    Maze Chest:                                          Treasure Chart 19
Mailbox:
    Letter from Hoskit's Girlfriend:                     Orange Rupee
    Letter from Baito's Mother:                          Orange Rupee
    Letter from Baito:                                   Piece of Heart
    Letter from Komali's Father:                         Treasure Chart 26
    Letter Advertising Bombs in Beedle's Shop:           Red Rupee
    Letter Advertising Rock Spire Shop Ship:             Triforce Chart 4
    Beedle's Silver Membership Reward:                   Silver Rupee
    Beedle's Gold Membership Reward:                     Red Rupee
    Letter from Orca:                                    Treasure Chart 35
    Letter from Grandma:                                 Treasure Chart 29
    Letter from Aryll:                                   Treasure Chart 39
    Letter from Tingle:                                  Piece of Heart
The Great Sea:
    Beedle's Shop Ship - 20 Rupee Item:                  Piece of Heart
    Salvage Corp Gift:                                   Skull Necklace
    Cyclos:                                              Treasure Chart 22
    Goron Trading Reward:                                Tingle's Chart
    Withered Trees:                                      Piece of Heart
    Ghost Ship:                                          Treasure Chart 34
Private Oasis:
    Chest at Top of Waterfall:                           Piece of Heart
    Cabana Labyrinth - First Chest:                      Treasure Chart 12
    Cabana Labyrinth - Second Chest:                     Knight's Crest
    Big Octo:                                            Piece of Heart
    Sunken Treasure:                                     Piece of Heart
Spectacle Island:
    Barrel Shooting - First Prize:                       Treasure Chart 37
    Barrel Shooting - Second Prize:                      Red Rupee
    Sunken Treasure:                                     Piece of Heart
Needle Rock Isle:
    Chest:                                               Piece of Heart
    Cave:                                                Triforce Shard 7
    Golden Gunboat:                                      Golden Feather
    Sunken Treasure:                                     Orange Rupee
Angular Isles:
    Peak:                                                Goddess Tingle Statue
    Cave:                                                Maggie's Letter
    Sunken Treasure:                                     Yellow Rupee
Boating Course:
    Raft:                                                Purple Rupee
    Cave:                                                Treasure Chart 18
    Sunken Treasure:                                     Triforce Chart 7
Stone Watcher Island:
    Cave:                                                Purple Rupee
    Lookout Platform Chest:                              Treasure Chart 2
    Lookout Platform - Destroy the Cannons:              Octo Chart
    Sunken Treasure:                                     Skull Necklace
Islet of Steel:
    Interior:                                            Red Chu Jelly
    Lookout Platform - Defeat the Enemies:               Piece of Heart
    Sunken Treasure:                                     Orange Rupee
Overlook Island:
    Cave:                                                Treasure Chart 24
    Sunken Treasure:                                     Piece of Heart
Bird's Peak Rock:
    Cave:                                                Power Bracelets
    Sunken Treasure:                                     Red Rupee
Pawprint Isle:
    Chuchu Cave - Chest:                                 Orange Rupee
    Chuchu Cave - Behind First Boulder:                  Magic Meter Upgrade
    Chuchu Cave - Behind Second Boulder:                 Yellow Rupee
    Chuchu Cave - Scale the Wall:                        Farore's Pearl
    Wizzrobe Cave:                                       Golden Feather
    Lookout Platform - Defeat the Enemies:               Triforce Chart 3
    Sunken Treasure:                                     Beedle's Chart
Thorned Fairy Island:
    Great Fairy:                                         Treasure Chart 1
    Northeastern Lookout Platform - Destroy the Cannons: Progressive Quiver
    Southwestern Lookout Platform - Defeat the Enemies:  Purple Rupee
    Sunken Treasure:                                     Orange Rupee
Eastern Fairy Island:
    Great Fairy:                                         Progressive Bow
    Lookout Platform - Defeat the Cannons and Enemies:   Silver Rupee
    Sunken Treasure:                                     Silver Rupee
Western Fairy Island:
    Great Fairy:                                         Treasure Chart 3
    Lookout Platform:                                    Golden Feather
    Sunken Treasure:                                     Progressive Wallet
Southern Fairy Island:
    Great Fairy:                                         Skull Hammer
    Lookout Platform - Destroy the Northwest Cannons:    Purple Rupee
    Lookout Platform - Destroy the Southeast Cannons:    Orange Rupee
    Sunken Treasure:                                     Skull Necklace
Northern Fairy Island:
    Great Fairy:                                         Deku Leaf
    Submarine:                                           Treasure Chart 31
    Sunken Treasure:                                     Tingle Tuner
Tingle Island:
    Ankle - Reward for All Tingle Statues:               Hyoi Pear
    Big Octo:                                            Red Rupee
    Sunken Treasure:                                     Silver Rupee
Diamond Steppe Island:
    Warp Maze Cave - First Chest:                        Progressive Bow
    Warp Maze Cave - Second Chest:                       Triforce Shard 2
    Big Octo:                                            Silver Rupee
    Sunken Treasure:                                     Orange Rupee
Bomb Island:
    Cave:                                                Nayru's Pearl
    Lookout Platform - Defeat the Enemies:               Piece of Heart
    Submarine:                                           Treasure Chart 5
    Sunken Treasure:                                     Golden Feather
Rock Spire Isle:
    Cave:                                                Joy Pendant
    Beedle's Special Shop Ship - 500 Rupee Item:         Empty Bottle
    Beedle's Special Shop Ship - 950 Rupee Item:         Wind Tingle Statue
    Beedle's Special Shop Ship - 900 Rupee Item:         Triforce Chart 8
    Western Lookout Platform - Destroy the Cannons:      Treasure Chart 25
    Eastern Lookout Platform - Destroy the Cannons:      Treasure Chart 23
    Center Lookout Platform:                             Piece of Heart
    Gunboat:                                             Empty Bottle
    Sunken Treasure:                                     Heart Container
Shark Island:
    Cave:                                                Piece of Heart
    Sunken Treasure:                                     Purple Rupee
Cliff Plateau Isles:
    Cave:                                                Din's Pearl
    Highest Isle:                                        Progressive Picto Box
    Lookout Platform:                                    Red Rupee
    Sunken Treasure:                                     Orange Rupee
Crescent Moon Island:
    Chest:                                               Yellow Rupee
    Submarine:                                           Silver Rupee
    Sunken Treasure:                                     Joy Pendant
Horseshoe Island:
    Play Golf:                                           Purple Rupee
    Cave:                                                Fill-Up Coupon
    Northwestern Lookout Platform:                       Green Chu Jelly
    Southeastern Lookout Platform:                       Piece of Heart
    Sunken Treasure:                                     All-Purpose Bait
Flight Control Platform:
    Bird-Man Contest - First Prize:                      Treasure Chart 4
    Submarine:                                           Progressive Bomb Bag
    Sunken Treasure:                                     Spoils Bag
Star Island:
    Cave:                                                Piece of Heart
    Lookout Platform:                                    Light Ring Chart
    Sunken Treasure:                                     Blue Rupee
Star Belt Archipelago:
    Lookout Platform:                                    Skull Necklace
    Sunken Treasure:                                     Piece of Heart
Five-Star Isles:
    Lookout Platform - Destroy the Cannons:              Treasure Chart 13
    Raft:                                                Ghost Ship Chart
    Submarine:                                           Treasure Chart 36
    Sunken Treasure:                                     Silver Rupee
Seven-Star Isles:
    Center Lookout Platform:                             Secret Cave Chart
    Northern Lookout Platform:                           Piece of Heart
    Southern Lookout Platform:                           Green Rupee
    Big Octo:                                            Treasure Chart 21
    Sunken Treasure:                                     Yellow Rupee
Cyclops Reef:
    Destroy the Cannons and Gunboats:                    Piece of Heart
    Lookout Platform - Defeat the Enemies:               Treasure Chart 8
    Sunken Treasure:                                     Hyoi Pear
Two-Eye Reef:
    Destroy the Cannons and Gunboats:                    Heart Container
    Lookout Platform:                                    Heart Container
    Big Octo Great Fairy:                                Purple Rupee
    Sunken Treasure:                                     Hurricane Spin
Three-Eye Reef:
    Destroy the Cannons and Gunboats:                    Treasure Chart 6
    Sunken Treasure:                                     Silver Rupee
Four-Eye Reef:
    Destroy the Cannons and Gunboats:                    Treasure Chart 30
    Sunken Treasure:                                     Treasure Chart 11
Five-Eye Reef:
    Destroy the Cannons:                                 Empty Bottle
    Lookout Platform:                                    Treasure Chart 20
    Sunken Treasure:                                     Purple Rupee
Six-Eye Reef:
    Destroy the Cannons and Gunboats:                    Orange Rupee
    Lookout Platform - Destroy the Cannons:              Piece of Heart
    Submarine:                                           Purple Rupee
    Sunken Treasure:                                     Piece of Heart
Gale Isle:
    Sunken Treasure:                                     Purple Rupee
Northern Triangle Island:
    Sunken Treasure:                                     Orange Rupee
Eastern Triangle Island:
    Sunken Treasure:                                     Orange Rupee
Southern Triangle Island:
    Sunken Treasure:                                     Purple Rupee

Starting island: Outset Island

Entrances:
  Dungeon Entrance On Dragon Roost Island:         Dragon Roost Cavern
  Dungeon Entrance In Forest Haven Sector:         Forbidden Woods
  Dungeon Entrance In Tower of the Gods Sector:    Tower of the Gods
  Dungeon Entrance On Headstone Island:            Earth Temple
  Dungeon Entrance On Gale Isle:                   Wind Temple
  Secret Cave Entrance on Outset Island:           Savage Labyrinth
  Secret Cave Entrance on Dragon Roost Island:     Dragon Roost Island Secret Cave
  Secret Cave Entrance on Fire Mountain:           Fire Mountain Secret Cave
  Secret Cave Entrance on Ice Ring Isle:           Ice Ring Isle Secret Cave
  Secret Cave Entrance on Private Oasis:           Cabana Labyrinth
  Secret Cave Entrance on Needle Rock Isle:        Needle Rock Isle Secret Cave
  Secret Cave Entrance on Angular Isles:           Angular Isles Secret Cave
  Secret Cave Entrance on Boating Course:          Boating Course Secret Cave
  Secret Cave Entrance on Stone Watcher Island:    Stone Watcher Island Secret Cave
  Secret Cave Entrance on Overlook Island:         Overlook Island Secret Cave
  Secret Cave Entrance on Bird's Peak Rock:        Bird's Peak Rock Secret Cave
  Secret Cave Entrance on Pawprint Isle:           Pawprint Isle Chuchu Cave
  Secret Cave Entrance on Pawprint Isle Side Isle: Pawprint Isle Wizzrobe Cave
  Secret Cave Entrance on Diamond Steppe Island:   Diamond Steppe Island Warp Maze Cave
  Secret Cave Entrance on Bomb Island:             Bomb Island Secret Cave
  Secret Cave Entrance on Rock Spire Isle:         Rock Spire Isle Secret Cave
  Secret Cave Entrance on Shark Island:            Shark Island Secret Cave
  Secret Cave Entrance on Cliff Plateau Isles:     Cliff Plateau Isles Secret Cave
  Secret Cave Entrance on Horseshoe Island:        Horseshoe Island Secret Cave
  Secret Cave Entrance on Star Island:             Star Island Secret Cave

Charts:
  Triforce Chart 1:  Greatfish Isle
  Triforce Chart 2:  Gale Isle
  Triforce Chart 3:  Stone Watcher Island
  Triforce Chart 4:  Outset Island
  Triforce Chart 5:  Cliff Plateau Isles
  Triforce Chart 6:  Southern Triangle Island
  Triforce Chart 7:  Seven-Star Isles
  Triforce Chart 8:  Two-Eye Reef
  Treasure Chart 1:  Private Oasis
  Treasure Chart 2:  Rock Spire Isle
  Treasure Chart 3:  Eastern Fairy Island
  Treasure Chart 4:  Southern Fairy Island
  Treasure Chart 5:  Thorned Fairy Island
  Treasure Chart 6:  Six-Eye Reef
  Treasure Chart 7:  Star Island
  Treasure Chart 8:  Western Fairy Island
  Treasure Chart 9:  Horseshoe Island
  Treasure Chart 10: Tingle Island
  Treasure Chart 11: Crescent Moon Island
  Treasure Chart 12: Five-Eye Reef
  Treasure Chart 13: Overlook Island
  Treasure Chart 14: Tower of the Gods
  Treasure Chart 15: Angular Isles
  Treasure Chart 16: Shark Island
  Treasure Chart 17: Ice Ring Isle
  Treasure Chart 18: Windfall Island
  Treasure Chart 19: Flight Control Platform
  Treasure Chart 20: Bomb Island
  Treasure Chart 21: Cyclops Reef
  Treasure Chart 22: Spectacle Island
  Treasure Chart 23: Diamond Steppe Island
  Treasure Chart 24: Northern Fairy Island
  Treasure Chart 25: Forsaken Fortress
  Treasure Chart 26: Northern Triangle Island
  Treasure Chart 27: Star Belt Archipelago
  Treasure Chart 28: Needle Rock Isle
  Treasure Chart 29: Mother and Child Isles
  Treasure Chart 30: Pawprint Isle
  Treasure Chart 31: Forest Haven
  Treasure Chart 32: Boating Course
  Treasure Chart 33: Five-Star Isles
  Treasure Chart 34: Eastern Triangle Island
  Treasure Chart 35: Islet of Steel
  Treasure Chart 36: Bird's Peak Rock
  Treasure Chart 37: Fire Mountain
  Treasure Chart 38: Three-Eye Reef
  Treasure Chart 39: Dragon Roost Island
  Treasure Chart 40: Headstone Island
  Treasure Chart 41: Four-Eye Reef

**Comment by LagoLunatic** [comment]
Not an issue, it's intended to work this way.

The "Playthrough" section lists all the progression item locations on this seed in the order you can obtain them. It lists progression items even if they're not actually required on this particular seed (such as the WT big key) if they could theoretically be required on other seeds with the same settings as your seed.

If you were to uncheck the option that allows progression items to appear in dungeons, big keys will no longer be considered progression items so they're definitely unneeded, so *then* none of them should appear in the spoiler log.

The "Playthrough" section is not intended to be the most efficient possible way of playing the seed while collecting the fewest possible items. On the contrary, if you got every item it told you to, it might be one of the least efficient ways of doing the seed. It's just a kind of visualization of "when can I get this item?", not a walkthrough.

**Comment by SirJubs** [comment]
Great Thanks! Keep up the great work!
