### ISSUE TITLE
[Suggestion] Starting unequipped

### ISSUE THREAD

**Issue by OlafurKrH** [LagoLunatic/wwrando#16]
It kinda feels like there should be a way to start without even the basic sword and have to settle for other weapons you find, like the hammer, bow, or even bombs until you get the first sword. And maybe the shield too. On that note, how about an option to start without the Ballad of Gales and perhaps the whole Wind Waker in general, but that can only be done if you choose to use the Swift Sail. More stuff to find, more randomness.

**Comment by LagoLunatic** [comment]
A mode where you don't start with the sword and shield is planned. It's just a huge amount of work to test what can and can't be done without a sword so it will take a long time.

I'm not planning to add a mode to start without wind waker/wind's requiem/ballad of gales. Would just be annoying, it wouldn't add new challenge or fun item interactions IMO.

**Comment by OlafurKrH** [comment]
okay then, the second part was probably not that good, though some would prob like it :P that first one, excited to try it out when possible.

**Comment by XerShade** [comment]
The main issue I could see with no sword is the game is designed to throw you in FF1's jail when a moblin catches you, regardless of where you are in the game. So getting stuck in FF1 could be an issue.

**Comment by JarheadHME** [comment]
It's been talked about before, if/when starting without a sword is implemented he said he'd just remove the code that causes that whole thing.

**Comment by OlafurKrH** [comment]
though just to clarify for those not in the know, I recently was screwing around with AR codes on a normal Wind Waker file, and FF is treated as the second visit unless you manage to get into the interior as PG pops up.

**Comment by LagoLunatic** [comment]
FF1 and FF2 are completely separate stages. FF1 isn't on the sea.
