### ISSUE TITLE
[Bug] "AggressivePeacefulLine" Is an Unbeatable Seed

### ISSUE THREAD

**Issue by Tippernockey** [LagoLunatic/wwrando#160]
The seed "AggressivePeacefulLine" appears to be unbeatable. The seed requires you to open Tower of the Gods in order to get the Command Melody. The mail minigame is also unlocked with Din's Pearl. In this seed you obtain Din's Pearl from the mail minigame, making the Command Melody unobtainable. The Hookshot and Grappling Hook are inside the Earth Temple and Wind Temple, which are required to beat the game.

**Comment by LagoLunatic** [comment]
>The mail minigame is also unlocked with Din's Pearl.

The mail minigame is beatable from the start. You must beat it 4 times, getting the requested amount of letters (or more) each time. After the 3rd time you have to exit and re-enter the room before you can do it the final time.
