### ISSUE TITLE
[Bug] Source not running in Linux

### ISSUE THREAD

**Issue by katawful** [LagoLunatic/wwrando#162]
I have Python 3.8 installed and the randomizer isn't running at all for me. It was running fine just a few weeks ago. I've cloned the git directly instead of using the release source archive. Here's the traceback:

```
Traceback (most recent call last):
  File "wwrando.py", line 10, in <module>
    from wwr_ui.randomizer_window import WWRandomizerWindow
  File "/home/kat/.local/share/Randomizers/wwrando/wwr_ui/randomizer_window.py", line 962, in <module>
    class ModelFilterOut(QSortFilterProxyModel):
TypeError: 'Shiboken.ObjectType' object is not iterable

**Comment by LagoLunatic** [comment]
Have you tried Python 3.6.6? That's the version the readme tells you to use, and as far as I'm aware newer and old versions won't work.

**Comment by katawful** [comment]
Hmm, weird. I thought Python 3.8 installed earlier than i remembered. Thank you
