### ISSUE TITLE
Wizzro Cave Chest Won't Spawn

### ISSUE THREAD

**Issue by Grip555** [LagoLunatic/wwrando#163]
Not only won't the chest spawn, but a lot of caves that have a similar layout also don't always spawn chests initially.

**Comment by LagoLunatic** [comment]
I think I've heard this happens sometimes if morths fall out of bounds and never die. Not sure since I haven't gotten it myself.
If you try over it should work eventually.

**Comment by Grip555** [comment]
I did the mission twice and I had the same problem.
