### ISSUE TITLE
Assertion Errors

### ISSUE THREAD

**Issue by mhmike88** [LagoLunatic/wwrando#164]
I downloaded the source for the randomizer, downloaded everything needed to run the program via the project command prompt, as prompted by the readme.txt attatched to the project. But I ran into an assertion error upon hitting the Randomize button.

Traceback (most recent call last):
  File "E:\Zelda randomizer files\Windwaker\wwrando-1.6.1\wwr_ui\randomizer_window.py", line 237, in randomize
    rando = Randomizer(seed, clean_iso_path, output_folder, options, permalink=permalink, cmd_line_args=self.cmd_line_args)
  File "E:\Zelda randomizer files\Windwaker\wwrando-1.6.1\randomizer.py", line 119, in __init__
    self.chart_list = self.get_arc("files/res/Msg/fmapres.arc").get_file("cmapdat.bin")
  File "E:\Zelda randomizer files\Windwaker\wwrando-1.6.1\randomizer.py", line 551, in get_arc
    arc = RARC(data)
  File "E:\Zelda randomizer files\Windwaker\wwrando-1.6.1\wwlib\rarc.py", line 25, in __init__
    assert self.magic == "RARC"
AssertionError

I've been wanting to try this randomizer for quite a while now, and was hoping some insight could be provided here because i'm not too keen on ideas for this.
Thank you for your time.

**Comment by LagoLunatic** [comment]
Sounds like your vanilla ISO is corrupted or something. Use dolphin to check if the md5 checksum of your vanilla ISO is d8e4d45af2032a081a0f446384e9261b. If not, you'll need to redump your ISO.

By the way, you know you don't need to run the randomizer from source on windows, right? You can just download the executable and run it normally. Running from source is for if you want to develop the randomizer, or if you're on mac/linux (which you don't appear to be).

**Comment by mhmike88** [comment]
I originally ran it from the source so i could obtain the proper python files to go with the randomizer. It was giving me drive path errors at first.

**Comment by LagoLunatic** [comment]
If you're running it from the executable, you don't need any python files.

If it's telling you you do, then show what that error message is exactly.

**Comment by mhmike88** [comment]
After I corrected the directories, both source and executable give me the error I listed above, i'm going to double check my iso now to see if a fresh copy will fix anything. I actually don't have dolphin however but if its the iso dump I think i know on my end what happened.

**Comment by mhmike88** [comment]
I appreciate you being so prompt by the way.

**Comment by mhmike88** [comment]
You were right, something was up with the iso, I didn't originally intend to use the source program when I started it up, but it gave me directory errors, after i corrected them, using the source program and installing all the directories, it gave me the error listed above. Don't really know why i didn't think to double check the iso before I came here. Thanks for your help.
