### ISSUE TITLE
Small Key Randomized Impossibly

### ISSUE THREAD

**Issue by dividedsoul17** [LagoLunatic/wwrando#167]
Dragon Roost Cavern has 4 small keys required to complete it. I have keys set to default but because the bird nest key doesnt register as a small key or something, it changed only that key and moved it to the big key. In order to get to the big key, you have to have the small key to get through the door. Therefore....impossible....sadly.

**Comment by LagoLunatic** [comment]
You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
