### ISSUE TITLE
Randomization/story optional?

### ISSUE THREAD

**Issue by MidnightApril** [LagoLunatic/wwrando#168]
Ok I know what you are thinking, its a randomizer that is what its supposed to do! But your randomizer also gives the ability to change the player character too. It would be nice to be able to play through the story as another character using your software to set up an iso so I can play through as zora link or one of the other models with the cut-scenes intact. Please consider this, thank you for your time.

**Comment by LagoLunatic** [comment]
I won't be adding this to the official version of the randomizer, but there's a fork of the randomizer by someone else that takes out the randomization while keeping the other features: <https://github.com/WideBoner/betterww>
