### ISSUE TITLE
[Suggestion] A Monster Hunter Mode Option

### ISSUE THREAD

**Issue by DGYucca** [LagoLunatic/wwrando#170]
Would there be a way to make it so all important items and hearts instead of being in chests etc , instead are monster drops. 

I think it would be an interesting game mode that would change up how the game gets played a fair bit. It would still also be able to follow a system of logic aswell as some enemies would be behind certain items.

**Comment by LagoLunatic** [comment]
Enemies in Wind Waker are not coded to be able to drop specific non-consumable items.

The only way to implement this feature would be to manually add two new parameters to every individual enemy in the game: one for the item ID to drop, and one for the flag to check to know if the player has already picked up the item it dropped or not so it knows to not drop it twice.
Implementing this for dozens of enemies would be an absolutely insane amount of work.

And besides, it would require at least 15 bits of space in each enemy's parameters for these parameters to fit, and many enemies use so many parameters already that they don't have the necessary space free, so it would be completely impossible for those enemies to drop items like any way you code.
