### ISSUE TITLE
[Suggestion]More big octos 

### ISSUE THREAD

**Issue by christopher842** [LagoLunatic/wwrando#172]
Is there a way to add more big octo battles into the sea? The battles with them are fun and it's satisfying to blow their eyes out with the bombs.

**Comment by Wiimeiser** [comment]
The problem would be flags. Also, Big Octos can only exist on flat seas and all flat sea islands that don't already have them are all main story islands. (They can be on rough seas, I glitched Tingle Island permanently once, but it doesn't look right and it's clear the seas are flat on those islands for a reason)

**Comment by LagoLunatic** [comment]
Adding more things to the game generally isn't the point of randomizer imo, it's randomizing the existing ones. There's also already a decent number of big octos in the game you can fight per run, so I don't see what adding more would do.
