### ISSUE TITLE
[Suggestion] switch between swift sail and regular sail

### ISSUE THREAD

**Issue by christopher842** [LagoLunatic/wwrando#173]
Is there a way that y'all would be able to implement switching between the swift sail and regular sail like how it is in the HD version? It can be a little challenging to stop with the swift sail especially if you are trying to get a treasure chart out of the sea and maybe the regular sail could be helpful in trying to slow down earlier.

**Comment by OlafurKrH** [comment]
You can pull out the Wind Waker for an instant stop.

**Comment by christopher842** [comment]
> You can pull out the Wind Waker for an instant stop.

Just out of curiosity... Would that be possible/easy to code into the game?
