### ISSUE TITLE
Possible bug in progression

### ISSUE THREAD

**Issue by AJRed** [LagoLunatic/wwrando#174]

**Comment by AJRed** [comment]
Sorry new to Github.
Permalink:  MS43LjAAUmVhZHlIZWFsdGh5RGF5bGlnaHQABwHDwAcQIAQAAAAAAAA=
I've consulted the spoilers and it seems to want me to collect Nayru's Pearl from the outset island great fairy in early part 4 of the walkthrough. However I cannot access the great fairy without bombs which I don't get until part 7, I tried collecting a progressive bomb bag but that didn't grant me access to bomb use.
Other than this I'm loving the ability to play a brand new Wind Waker! Thanks for all the hard work!

**Comment by LagoLunatic** [comment]
>I cannot access the great fairy without bombs

Power bracelets lift boulders

**Comment by AJRed** [comment]
Racked my brain for hours on that one, Thanks so much for the quick response. 
Cheers!
