### ISSUE TITLE
bombs caused dead run

### ISSUE THREAD

**Issue by FunnyHahaMan** [LagoLunatic/wwrando#180]
For me, the bombs spawned in one of the lookout platforms that required the cannons on the tower to be destroyed to spawn the chest. Since you can only destroy the cannons with bombs I cannot progress. The seed i used was TenWhoppingIdiot. I dont know if you are able to restrict the spawn for bombs to lookout platforms that dont require destroying the cannons or not but if you can that would be awesome. Love the mod so far by the way great job!

**Comment by LagoLunatic** [comment]
>Since you can only destroy the cannons with bombs I cannot progress.

Boomerang destroys cannons
