### ISSUE TITLE
[Suggestion] Chest Type Matches Contents

### ISSUE THREAD

**Issue by NateFelix73** [LagoLunatic/wwrando#183]
Hi,

So on other randomizers, such as Ocarina of Time and Majora's Mask, they have a feature where chest size matches contents (such as, a Boss Key would be found in a Boss Key chest, a refill item or low rupee amount would be found in a small wooden chest, etc).

Is this possible to have done in Wind Waker, but instead have it be chest TYPE matches contents? (For example: the chest on Mother and Child Isles could be a wooden chest if its randomized contents is something found in a wooden chest, and a Boss Key chest could be a spiked chest if its randomized contents is something found in a spiked chest).

Also, would it be possible to do this with the sunken treasure chests also? (Example: have the sunken treasure chests be found on islands, in dungeons, etc., and have wooden, spiked, and other chests be chests that Link can get from the Great Sea.)

Thank you for considering this!

**Comment by LagoLunatic** [comment]
Won't do this since it would effectively spoil whether the item in a chest is good or not ahead of time.

> Also, would it be possible to do this with the sunken treasure chests also? (Example: have the sunken treasure chests be found on islands, in dungeons, etc., and have wooden, spiked, and other chests be chests that Link can get from the Great Sea.)

Not possible, salvage chests are a separate object from treasure chests.
