### ISSUE TITLE
Unexpected Removal of "Invert Y-Axis" Option

### ISSUE THREAD

**Issue by ChoiceSuperG** [LagoLunatic/wwrando#184]
In the transition of moving to 1.8 it appears that the "invert Y-axis" option for the randomizer has been removed but not the "invert X-axis". I actually use both so its kinda a bummer.

**Comment by LagoLunatic** [comment]
There's never been an "invert Y-axis" option to begin with. I'm curious to hear how you used something that didn't exist.
