### ISSUE TITLE
Map opening bug 

### ISSUE THREAD

**Issue by SoulBunrer395** [LagoLunatic/wwrando#185]
Every time I go to open the map, the game freezes, I'm just wondering if there is anything I could do to fix this. Thank you and have a good day!

**Comment by LagoLunatic** [comment]
What emulator and version are you using?
I recommend a relatively recent beta or development version of Dolphin: https://dolphin-emu.org/download/
If you're using a stable version of Dolphin it's probably an emulator bug so just upgrade.

And what's the md5 hash of your vanilla WW iso, before randomizing? Right click -> Properties -> Verify -> Verify Integrity in Dolphin.
It should be d8e4d45af2032a081a0f446384e9261b - if not, your iso is corrupted.

**Comment by SoulBunrer395** [comment]
Thank you! It worked.
