### ISSUE TITLE
Problem with Picture Sidequests

### ISSUE THREAD

**Issue by FatBoySlim2000** [LagoLunatic/wwrando#186]
When doing the picture sidequests, like becoming Lenzo's Assistant and Pompie and Vera, they won't accept any pictures at all. We've always taken the pictures the same way we always have and it worked, but now they're having problems accepting the pictures. Don't know if this is a bug or anything but it's driving me insane lol.

**Comment by LagoLunatic** [comment]
Not a bug, the game is just extremely picky about the pictographs because of wonky detection. You may be doing something wrong like the zoom or timing, or you may be unlucky. Feel free to asks for tips in the discord server.
