### ISSUE TITLE
Version 1.8.0 falsely detected as trojan

### ISSUE THREAD

**Issue by bendashie** [LagoLunatic/wwrando#187]
Attempting to download the latest version results in antivirus software marking it as a trojan horse. While I initially thought it was exclusive to avast, I tested it with other antiviruses, and they too mark the exe as malware. Obviously these are false positives, so I am curious as to why this might be happening. This issue does not occur in any other version, only 1.8.0.

I'm not sure if something can be done about this besides reporting it as a false positive, but I wanted to shed light on the issue.

**Comment by LagoLunatic** [comment]
I'm aware, a number of people have had the same issue.
The only thing that comes to mind that changed in 1.8.0 is that I upgraded the Python version I use from an old one to a recent one (3.8.2). Presumably the antivirus programs haven't seen Python 3.8.2 before so they just assume it's a virus. Nothing I can do about that, but maybe the antivirus programs will stop marking it as a trojan in the future after they've had time to get used to newer Python versions or whatever.
