### ISSUE TITLE
Nintendont can't read the disc header

### ISSUE THREAD

**Issue by NQNStudios** [LagoLunatic/wwrando#190]
I generated 2 isos, one with almost everything random and another with the default settings. I'm using Nintendont Loader v6.489 on my Wii with Homebrew channel. I added both of those to my SD card along with the original wind waker iso, all in the proper directory structure (though I did leave the text files in the generated folders on there, so I guess that's one difference).

Nintendont is listing the two generated ROMs in red text and says this when I select either of them:

![IMG_20200906_193821](https://user-images.githubusercontent.com/2584745/92340692-97b22e00-f078-11ea-9774-4b7c603f9ce7.jpg)

Nintendont then crashes and sends me back to the Homebrew channel. My first instinct is that the randomizer is changing this header somehow. 

(maybe I need to update my nintendont version or take the bug report up with that project, or just play with Dolphin on a PC.)

**Comment by NQNStudios** [comment]
Actually, wait, it's happening for all of my ROMs, not just the generated ones. Maybe this has nothing to do with the randomizer

**Comment by LagoLunatic** [comment]
Indeed, the randomizer is known to work on nintendont
