### ISSUE TITLE
Dragon Roost Cavern Glitch

### ISSUE THREAD

**Issue by macncheeseface** [LagoLunatic/wwrando#191]
Permalink: MS44LjAAUHJvZmVzc2lvbmFsRmFtaWxpYXJEZWJ1dGFudGUAv32vAA8AAAgAAAAAAAAA
When I got to Dragon Roost Cavern, there is no way to get the second key for the second locked door. I checked the spoiler log and the key spawns behind the locked door. This made the run impossible so I had to make a new one and restart.

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl

**Comment by macncheeseface** [comment]
Damn I already erased the old run files. I wish I kept them Thank you so much though for the quick response, I greatly appreciate it.
