### ISSUE TITLE
[Feature Request] Start without sword (not swordless)

### ISSUE THREAD

**Issue by hairybones** [LagoLunatic/wwrando#192]
I was wondering how possible it would be to implement a randomizer where the sword + master sword are just items in the mix? You get the regular sword like any other item at the beginning of the game, and while you get the master sword from a cutscene, there's still an option to not start with the master sword and find it in the world. Without having any much programming knowledge at all, this implementation still seems like a safe bet and a fun way and challenging new way to start a run.

**Comment by LagoLunatic** [comment]
This already exists. It's called "Randomized Sword" in the current version and is being renamed to "No Starting Sword" for the next version.
