### ISSUE TITLE
Impossible dragon roost cavern?

### ISSUE THREAD

**Issue by Cyler1** [LagoLunatic/wwrando#194]
I'm trying to get through drc but I can't get to anything past the first 3 chest since I've only found 1 small key. The tracker says I can't progress any further until I find another key and when I checked the spoiler log it's showing the rest of the keys as being passed the locked door. I don't have Key-Lunacy enabled so I really don't know if there's just something I'm missing or if I just got a bugged seed.

Spoiler log/seed
[WW Random LegitimateFormidablePinnacle - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/5468324/WW.Random.LegitimateFormidablePinnacle.-.Spoiler.Log.txt)

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
