### ISSUE TITLE
Suggestion: Option for vanilla placements

### ISSUE THREAD

**Issue by toasterrabbit** [LagoLunatic/wwrando#196]
I was wondering if you could add an option for a completely vanilla placements and also story cutscenes. I'd like to play through the story with custom models and I know alot of other people do and your program is an easy way to add those to WW isos. Thank you

**Comment by LagoLunatic** [comment]
I won't add that to the randomizer, but somebody else made a fork of the rando that does what you want https://github.com/WideBoner/betterww
