### ISSUE TITLE
Bug? Phantom Ganon at Ganon's Tower Unable to Be Hit?

### ISSUE THREAD

**Issue by MinteaMari** [LagoLunatic/wwrando#199]
This is my first randomized Wind Waker file, (_though I have experience with the original_), so I've been patient with the process, but I'm having an issue where the dead man's volley (hitting the ball back to Phantom Ganon in the tower) is not hitting him _at all_. The auto-target unlocks a split second before it would hit him and he disappears without being hit. I have the fully powered up Master Sword and have also volleyed with the empty bottle with no luck.  I spent three full hours on this and my roommates agreed several volleys should have hit.

Light arrows do defeat him, but the maze chest does not drop, which I am looking to get. (_I reloaded without saving after I tested the light arrow_.) I have a nearly 100% collectible game, only missing one heart piece and a couple of misc items locked behind the item Phantom Ganon would drop. I can technically move on by using the light arrow, but this seemed important to report.

The permalink for this seed is:
MS44LjAAQW5jaWVudEVpZ2h0U2hyaW1wbGV0AF/f44EPAEAIAABAAAAwAA==

Thank you for reading and your time, Mari

**Comment by LagoLunatic** [comment]
There are 3 different version of Phantom Ganon in the game: The Forsaken Fortress one, the Ganon's Tower maze one, and the Ganon's Tower central room one.

> Light arrows do defeat him

This is only true of the final one in the central room, so that must be the one you're trying to fight, since light arrows pass right through the other two versions.
But that one is unrelated to the maze chest. You only have to go through the maze fighting the Phantom Ganon in there to get the maze chest, and can ignore the central room one until you want to beat the game.

>The auto-target unlocks a split second before it would hit him and he disappears without being hit.

The reason Nintendo coded the 3rd version like this is to force you to use light arrows to progress.

**Comment by MinteaMari** [comment]
> But that one is unrelated to the maze chest. You only have to go through the maze fighting the Phantom Ganon in there to get the maze chest, and can ignore the central room one until you want to beat the game.

The maze never appeared. The game put me straight into the Phantom Ganon fight,

**Comment by MinteaMari** [comment]
> > But that one is unrelated to the maze chest. You only have to go through the maze fighting the Phantom Ganon in there to get the maze chest, and can ignore the central room one until you want to beat the game.
> 
> The maze never appeared. The game put me straight into the Phantom Ganon fight,

Nevermind. I think I figured out what you mean. It's really easy to miss. Thank you for the quick reply/help.

**Comment by MinteaMari** [comment]
> > > But that one is unrelated to the maze chest. You only have to go through the maze fighting the Phantom Ganon in there to get the maze chest, and can ignore the central room one until you want to beat the game.
> > 
> > 
> > The maze never appeared. The game put me straight into the Phantom Ganon fight,
> 
> Nevermind. I think I figured out what you mean. It's really easy to miss. Thank you for the quick reply/help.

I just tried to go through the side rooms without starting the Phantom Ganon fight and the fight auto-started, even when avoiding the middle and going around the edge.

**Comment by LagoLunatic** [comment]
> I just tried to go through the side rooms without starting the Phantom Ganon fight and the fight auto-started, even when avoiding the middle and going around the edge.

Dunno why that matters. Even if PG3 started just ignore him. Go fight PG2.

**Comment by MinteaMari** [comment]
> Dunno why that matters. Even if PG3 started just ignore him. Go fight PG2.

I can't go fight PG2 because the side rooms don't lead into the maze. They lead into the rooms with the torches and the crystal switches. The maze is completely skipped and I have no idea why.

**Comment by LagoLunatic** [comment]
Just drop down the hole m8. The game even hints at it

**Comment by MinteaMari** [comment]
> Just drop down the hole m8. The game even hints at it

That's what I'm supposed to do? I'll try it, thanks. It just never occurred to me to jump there. The text made me think it was talking about the portal to FF through the other side. Thank you for guiding me through this.
