### ISSUE TITLE
WT Softlock

### ISSUE THREAD

**Issue by cskoczylas** [LagoLunatic/wwrando#2]
I ran into an issue where the game would softlock in Wind Temple if you went through one of the warp pipes without moving Makar to another room. I have all 3 warp pots unlocked, if that would change anything.

https://www.youtube.com/watch?v=L-osGbeOxHo

Permalink: MS4wLjAASUxvVkVUaWdzZXJzAONrHAAA

**Comment by LagoLunatic** [comment]
I can't seem to reproduce this. Can you upload your save file?

**Comment by cskoczylas** [comment]
Unfortunately the save file is already modified (beat the dungeon) and I can't get the softlock again.
