### ISSUE TITLE
Zelda player model does not change colors correctly

### ISSUE THREAD

**Issue by KLPD123** [LagoLunatic/wwrando#202]
Hi, I was trying to play with Zelda's model, but changing her dress color only affects the lower portion of her dress and not the shirt. Below are screenshots of the preview and then in game. I submitted this issue on SageOfMirror’s repository for wind waker models, but I haven’t heard a response so I was hoping you could help me out. Is this an issue on my end or with the model?
![DC6B1606-21CA-4DE2-8198-1A7FE9EC9C2D](https://user-images.githubusercontent.com/47219856/103191657-c102fe00-48a3-11eb-9235-e59754022eae.png)
![5C4AF009-3700-4C30-8E09-F176A8CD33FE](https://user-images.githubusercontent.com/47219856/103191659-c2342b00-48a3-11eb-9a08-e601f0461cbb.png)

**Comment by LagoLunatic** [comment]
It's an issue with the model, I told the creator about it when you posted your other report and they said they'll fix it
