### ISSUE TITLE
Cannot progress in dragon roost.

### ISSUE THREAD

**Issue by Nyx2** [LagoLunatic/wwrando#21]
I cannot get the Chest Across Lava Pit I think thats the one (it's the room that also has a switch in it that opens the door). Which i can't progress in dragon roost without the key in that chest, but it would require either Deku Leaf or grappling hook.  I can't get grappling hook because it's in Lenzo's House - Left Chest which i can't get to without leaf. I can't get leaf because it's  Jalhalla's Heart Container which i can't get to without mirror shield which is in the Pot Room Chest that i can't get to because i can't get the small key in the first chest i talked about. Permalink: MS4yLjAAUG9zc2libGVBbGlrZVF1aWxsAAcR6wEAAw==

**Comment by LagoLunatic** [comment]
> I can't get grappling hook because it's in Lenzo's House - Left Chest which i can't get to without leaf.

Activate the windmill, and ride the carriage until you're above lenzo's house, fall down and you can enter.

**Comment by OlafurKrH** [comment]
yeah its bit of a tricky jump, but if you can activate the windmill, you can just hop to it without the leaf.

**Comment by Nyx2** [comment]
Oh, ok sorry to bother you.
