### ISSUE TITLE
Saving the game corrupts memory card

### ISSUE THREAD

**Issue by ethanccss** [LagoLunatic/wwrando#210]
I got stuck on dragon roost (no grapple). Saving failed, made a new memory card, saving worked, but when trying to reload the game claims the card is corrupt and needs to be formated. 

Dolphins memory card manager states "mismatch between internal data structures". Other games work but as soon as I save in randomized wind waker it corrupts the card. Can't continue as the last save state was also stuck on top of Dragon roost.

**Comment by LagoLunatic** [comment]
You need to include more info for how to reproduce the issue.
Upload your spoiler log, what exact version of dolphin are you using, does the save get corrupted if you start a new game and try to save right at the start? etc
