### ISSUE TITLE
Progressive Bow issue

### ISSUE THREAD

**Issue by DaDaged** [LagoLunatic/wwrando#212]
so I have done all locations possible, and I checked the spoiler log on where to get the different bows. One was in Oasis (which it was), 2nd was Gunboat at rockspire (which it was), but the 3rd one is the problem. it says that its supposed to be the stock flower from Zunari, but that was the flower itself for me. 
[WW Random UncleanMessyEvent - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/5935487/WW.Random.UncleanMessyEvent.-.Spoiler.Log.txt)

**Comment by LagoLunatic** [comment]
The Goron trading starter item is not randomized, it's always the Town Flower.

The reward he gives you after you've progressed the quest to the point that Exotic Flower is available (which was Magic Armor in the vanilla game) is the one that's randomized.
