### ISSUE TITLE
Logic Bug?

### ISSUE THREAD

**Issue by nintendesi** [LagoLunatic/wwrando#214]
Hello, I wanted to write about a potential issue I may have encountered when playing a seed a few days back. Basically, I had to go to pull the vanilla Master Sword check in Hyrule and fight the two Mighty Darknuts there to receive my first Progressive Bow, and that allowed me to get my Deku Leaf, other Progressive Bows, and eventually my first Progressive Sword. At the time, I thought this was unnecessarily difficult, but I read the spoiler log and I assumed that this must have been in the logic. I recently came across [this line of text in the logic](https://github.com/LagoLunatic/wwrando/blob/master/logic/macros.txt#L409), which contradicts my assumption. The Permalink for the seed is MS44LjAAR2F5RmluZ2VyAAMQBAAPUAAEAAAAAAAAAA== and the Seed name is GayFinger (to provide some context, I stream, and we have a very queer community). I've also attached the spoiler log itself here: [WW_Random_GayFinger_-_Spoiler_Log.txt](https://github.com/LagoLunatic/wwrando/files/5948971/WW_Random_GayFinger_-_Spoiler_Log.txt). I hope that this information is helpful, in case this is indeed a bug that I have found. If not, I am very curious as to what I was supposed to do in this seed. Thank you so much for all of your help. This is a fantastic randomizer, and I've just adored all of the effort and passion that the community has put into the project!

**Comment by LagoLunatic** [comment]
> I recently came across [this line of text in the logic](https://github.com/LagoLunatic/wwrando/blob/master/logic/macros.txt#L409), which contradicts my assumption.

It was changed since the last version because it's too difficult. In the existing released version that is required, in the next one coming out soon it's not.

**Comment by nintendesi** [comment]
Oh, that makes so much more sense. Thank you so much!
