### ISSUE TITLE
Potential Bug in Wind Temple

### ISSUE THREAD

**Issue by nintendesi** [LagoLunatic/wwrando#216]
Hello, I was playing a Beta seed earlier today (I'll attach the spoiler log at the end of this message). I was very close to finishing the seed, I only needed a Hookshot, Mirror Shield, final Progressive Sword, and one more Triforce Shard to reach Ganon. If I am reading the spoiler log correctly and understand how to navigate the Wind Temple properly, I believe the seed is bugged. According to the spoiler log, the Hookshot is in the Chest Behind Seven Armos. My understanding was that to reach this room, you need to open the middle floor in the hub area of the Wind Temple, and without the Hookshot, I don't see a way to reach there. I spent about an hour in the Wind Temple trying to find a way to reach that area, before consulting to spoiler log to verify the location of the Hookshot. If there is something I'm missing as to how the floor is supposed to open without the Hookshot, I apologize for reporting a bug, and I would appreciate any advice on this. Thank you so much, and again, I really appreciate all of the work that you have been putting into this randomizer!
[WW_Random_GaycationLink_-_Spoiler_Log.txt](https://github.com/LagoLunatic/wwrando/files/6012837/WW_Random_GaycationLink_-_Spoiler_Log.txt)

**Comment by JarheadHME** [comment]
You need to have makar plant the two trees at the bottom of the hub room to turn the fan on

**Comment by nintendesi** [comment]
Thanks for the response, I appreciate that very much. Oh, I did not realize that the other end of the cyclones room connected to the ledge with the Iron Boots switch. I apologize for taking your time, but I very much appreciate your help. Thanks again for the prompt reply and all the help!
