### ISSUE TITLE
Possible Progression Block?

### ISSUE THREAD

**Issue by MYoshua64** [LagoLunatic/wwrando#218]
Hello,
I'm running a randomizer made with version 1.8.0, premalink is: MS44LjAATGVnZW5kYXJ5TWlzZXJhYmxlSHlydWxlAAcNogAPAEAMAAAAAAAAAA== 
and I got a bit stuck.  Spoiler Log advised me to get progression items (including the Command Melody) through destroying cannons on lookout platforms, which requires bombs. Spoiler Log lists bombs as Gohma's Heart Container in DRC, the entrance to which has been randomized to be on Gale Isle (again, according to Spoiler Log). To enter Gale Isle, I need the Hammer, which is listed in WT dungeon. Unfortunately, I cannot get through the first room of the Wind Temple without the Command Melody, as I need Makar to turn off the fans. And as I wrote earlier, I need bombs to get the Command Melody.
I'd be happy to know if I've missed something in this cycle or is this an issue with the randomizer. I'll update to version 1.9.0 to be sure.
Thanks!

**Comment by LagoLunatic** [comment]
Boomerang destroys cannons

**Comment by MYoshua64** [comment]
Oh I'm dumb. Thanks! Never knew that
