### ISSUE TITLE
Bug Letter from Baito

### ISSUE THREAD

**Issue by Uief000** [LagoLunatic/wwrando#219]
Hi, Im sorry to write this but i have a problem. I make the mini-game of Baito on Dragon Roost Island And and he give me a Triforce Shard after that i go take the note of mom and i send it on the mailbox and later le lettre give me Treasure Chart 36 But Baito don't send me the Din's Pearl and i am lock because the Grappling Hook is on the tower of the god. 

[WW_Random_StiffIncredibleNayru_-_Spoiler_Log.txt](https://github.com/LagoLunatic/wwrando/files/6054605/WW_Random_StiffIncredibleNayru_-_Spoiler_Log.txt)

thank you if you can help me.

**Comment by OlafurKrH** [comment]
If you haven't yet, you need to complete Earth Temple, that triggers the Baito letter.

**Comment by Uief000** [comment]
okey thank you i go make the  Earth Temple .
