### ISSUE TITLE
[Suggestion] Remove Unnecessary Treasure Charts from Playthrough

### ISSUE THREAD

**Issue by cmcoffin** [LagoLunatic/wwrando#220]
Hi,

I was wondering if it would be possible to remove the charts that don't contain progress items from the playthrough section of the spoiler log. As it stands it puts all 49 charts in the playthrough and it's non trivial to pull out only the meaningful ones. I'm eorking on implementing this myself, but the code's a little over my head.

Thanks

**Comment by LagoLunatic** [comment]
The playthrough section lists all progress items under the current settings, regardless of whether the progress item is actually required to finish the game on this particular seed or not. For example, if you happen to get a seed where none of the required items are locked behind Deku Leaf, Deku Leaf will still be listed in the playthrough section. The playthrough section is not intended to give you the most efficient possible path through the seed, so I don't intend to change this behavior.

**Comment by cmcoffin** [comment]
Ah I see, I guess it was misunderstanding that all charts are considered progress items regardless whether they lead to a progress item or not. Thanks for replying quickly.
