### ISSUE TITLE
Unable to run wwrando.py on macOS Big Sur

### ISSUE THREAD

**Issue by JayBirdGuru** [LagoLunatic/wwrando#225]
I have not been able to successfully run wwrando.py on macOS. The version I am running is 11.2.3 Big Sur. Once I run "python3 wwrando.py" from Terminal, the Python Launcher opens but does not present the GUI. It just sits there and gradually consumes more memory until the program crashes or I kill it off.

I do have Python 3.8 installed, and all the required packages as well.

Some things I have tried, with the same results:
-Running the most updated version of Python (3.9.2)
-Running various versions of Python 3.8
-Updating PyYAML and Pillow packages to latest versions

I am able to run other python programs successfully (both GUI and non-GUI). It is just wwrando.py that is giving me issues.

Any pointers are appreciated. Thanks!

**Comment by LagoLunatic** [comment]
I've never used a mac in my life so I won't be able to help, but you may want to consider posting in the discord server too in case maybe someone there uses the randomizer on mac.

**Comment by JayBirdGuru** [comment]
I was able to figure it out. There's some extra security applied to the Terminal in Big Sur that makes it a pain to run some third-party scripts. I was able to get around that by running it from the Python shell that gets installed with the official distribution. Not pretty but it works.

**Comment by lotachiamaka** [comment]
Can you give more detail on how you solved this issue. I've also been unable to get it to run on BigSur, but Im not sure what you mean by the python shell installed with the official distribution. Im currently on python 3.9.5

**Comment by JayBirdGuru** [comment]
If you installed Python from www.python.org/downloads, the package should have installed 2 applications along with the runtime - IDLE.app and Python Launcher.app. IDLE.app is just a bare-bones Python shell that can run .py files, but it does so a lot better than Apple's built-in Terminal.app. Assuming you have the libraries from requirements.txt installed, you should be able to right-click wwrando.py and open with IDLE. That's what ended up working for me.

**Comment by lotachiamaka** [comment]
yes that worked for me as well, thanks!
