### ISSUE TITLE
I am softlocked in dragons roost cavern

### ISSUE THREAD

**Issue by Hiderlink20** [LagoLunatic/wwrando#228]
Permalink: MS45LjAARnV0YW5hcmlJbmZsYXRpb25GZXRpc2gA//0fAA8QQAMAAQAAAAEAAA==

I was going through the dragon's roost cavern and I found myself locked out of the dark room with no key to get.  After consulting a walkthrough, I learned that I was supposed to get the key from the bird's nest nearby but it instead had an orange ruppee.  I then look in the spoiler log and not only are the remaining keys past the dark room, but defeating the boss would've given me the boomerang which I needed for the Deku forest dungeon.  In the future, I would like for there to be an option to toggle whether or not the items in the dungeons are randomized so they stay in their original spot.

**Comment by LagoLunatic** [comment]
You're not softlocked, you just need to use the deku leaf to sequence break and get the small keys in the Big Key Chest and the Tingle Statue Chest. Not randomizing items would defeat the purpose of a randomizer. Also good seed name

**Comment by Hiderlink20** [comment]
ok thank you
