### ISSUE TITLE
Preparing for multiplatform releases

### ISSUE THREAD

**Issue by EthanArmbrust** [LagoLunatic/wwrando#229]
Hello,
I've been working on a branch that will build release binaries automatically through GitHub Actions for Windows, macOS, and Linux. Before I open a PR, I would like your input on a handling the settings.txt and custom models folder.
  
On macOS, I think it makes the most sense to bundle the program as a .app bundle. This makes sticking a settings file and custom models folder next to the Unix executable in the app bundle a bad option, as it's not very user-accessible and will be overwritten if the app is updated. My proposed solution is to use the [appdirs](https://pypi.org/project/appdirs/) package to place the settings file and custom models folder in a platform-specific user data folder. I think it would be a good idea to default to this for all platforms, but attempt to load settings and models from the current directory first on non-Mac platforms. This would ease the transition for Windows users updating from an older version.  

What are your thoughts on this?

**Comment by LagoLunatic** [comment]
> On macOS, I think it makes the most sense to bundle the program as a .app bundle.

What is a ".app bundle"? Is it like installing a program to "Program Files" on Windows? Does Mac not have a way to run standalone program executables?

> My proposed solution is to use the [appdirs](https://pypi.org/project/appdirs/) package to place the settings file and custom models folder in a platform-specific user data folder. I think it would be a good idea to default to this for all platforms, but attempt to load settings and models from the current directory first on non-Mac platforms.

How would users install custom model packs? Would the randomizer UI have a new button to load a zip and install them to the appropriate directory automatically, or would the user have to find that directory and put them there manually?

> What are your thoughts on this?

Sounds a bit annoying for development (both rando dev and custom model dev) if the settings.txt and custom models are off in a weird directory. Would be doable obviously, but it seems like a bit of a pointless change if there are other options.

**Comment by EthanArmbrust** [comment]
>What is a ".app bundle"? Is it like installing a program to "Program Files" on Windows? Does Mac not have a way to run standalone program executables?  

An .app bundle is the standard way of packaging and distributing applications on macOS. They're essentially a directory containing a metadata file, an icon set, the Unix executable, and any other data the program might need. They run by just clicking on the app. They can be copied to the "/Applications" folder similar to "C:\Program Files" on Windows, but this is not necessary.   It is possible to distribute just the Unix executable on its own, but this has a number of downsides. Mainly, you can't run the executable by clicking on it; it must be run from a terminal. Also, there is no icon for the program in the file manager.

>How would users install custom model packs? Would the randomizer UI have a new button to load a zip and install them to the appropriate directory automatically, or would the user have to find that directory and put them there manually? 

I haven't changed anything about how models are installed so far. The only difference is the location of the models folder. I do think it would be a good idea to have a button next to the model drop-down to install a model from a zip file. This shouldn't be too hard for me to implement.

>Sounds a bit annoying for development (both rando dev and custom model dev) if the settings.txt and custom models are off in a weird directory. Would be doable obviously, but it seems like a bit of a pointless change if there are other options.

My implementation would first attempt to load the settings.txt and models from the current working directory, the same way that the randomizer currently does. Only if those files are nonexistent will it try to load from a user data directory.  This would allow devs and users to keep the current workflow for non-Mac platforms if desired.  

If you're really against using the APPDATA folder on WIndows at all, I could make these changes Mac only.

**Comment by LagoLunatic** [comment]
I guess the part I'm confused about here is why the files will be "overwritten" on update in the first place, thus requiring a separate directory to be used. When updating the randomizer on Windows if you want to keep your settings.txt and custom models you'd manually copy them from the old randomizer directory to the new one. Why does this not work on Mac?

**Comment by EthanArmbrust** [comment]
Because the settings.txt file would get placed next to the unix executable within the app bundle. When a user would go to update, they would place the new .app over the old one and the entire bundle would be replaced by the new one.
```
Wind\ Waker\ Randomizer\ 1.9.0_64bit.app/
└── Contents
    ├── Frameworks
    ├── Info.plist
    ├── MacOS
    │   ├── Wind\ Waker\ Randomizer\ 1.9.0_64bit  <-- unix executable
    │   └── settings.txt
    └── Resources
        └── icon.icns
```

**Comment by LagoLunatic** [comment]
I see, so a .app is basically like a zip file, that makes sense.

I [slightly refactored](https://github.com/LagoLunatic/wwrando/commit/635441cf5a317d666d1ce1f3cf18041b438cdcad) the code so it doesn't hardcode those paths and loads them from wwrando_paths.py. (Your fork's implementation of this had several bugs.)

For now I think it'd be better to only use the appdirs stuff on Mac and leave it as is for Windows/Linux.

The button that installs a zip with custom models I think would be a good idea for all OSes since some users get confused about directory structures and that should be automatically detectable. Just can't decide where the button would actually look good in the UI.

**Comment by EthanArmbrust** [comment]
I've finished writing the function to install a custom model zip file. Let me know if you think of a good a place to put a button.

**Comment by LagoLunatic** [comment]
Tried several places, this is the best one I could find:
![image](https://user-images.githubusercontent.com/19174152/115937245-7403f280-a465-11eb-8798-db85701463ff.png)

**Comment by EthanArmbrust** [comment]
Closing this and opening a PR
