### ISSUE TITLE
Possible logic bug?

### ISSUE THREAD

**Issue by caus909** [LagoLunatic/wwrando#234]
Hello,
On the seed MS45LjAAU2hhZHlXb3JyaXNvbWVFbG1hAP//f4AOQEADAAAAAAABAAA= I generated, we're finding ourselves kind of stuck.
Indeed, the logic says that after the first "Progressive bow" gotten at Dragon Roost Island, we should go to the fire mountain to get the delivery bag. But we didn't obtain the Ice/Fire arrows, and nothing in the logic mentions them, both prior, nor after. They don't even appear at all in the item list. At first I thought they had been unlocked automatically with the bow since they don't appear anywhere in the spoiler log, but it doesn't seem so, only normal arrows are.
Am I missing something here?

Thanks in advance for your answer

**Comment by LagoLunatic** [comment]
It does not say that the Delivery Bag is inside Fire Mountain. It says the Delivery Bag is at "Fire Mountain - Lookout Platform Chest", which requires no items to get.

> But we didn't obtain the Ice/Fire arrows, and nothing in the logic mentions them, both prior, nor after. They don't even appear at all in the item list.

Fire and Ice Arrows are the second bow upgrade. They're not in one specific place, just whichever of the 3 bow upgrades you happen to get second.
