### ISSUE TITLE
Logic Bug, Pearl in hyrule master sword chamber 

### ISSUE THREAD

**Issue by KBequinox** [LagoLunatic/wwrando#237]
[WW Random StunningWholeCaptive - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/6567185/WW.Random.StunningWholeCaptive.-.Spoiler.Log.txt)

Skull hammer was in tower of gods boss heart piece and one of the pearls was in the hyrule castle master sword chamber. far as I can tell that means you can never actually make the tower of the gods appear.

**Comment by OlafurKrH** [comment]
Hyrule only requires the 8 triforce pieces, not the three pearls.

Don't worry, you're not the first to make this mistake and certainly won't be the last.
