### ISSUE TITLE
Soft Lock in Dragon Roost Island

### ISSUE THREAD

**Issue by hamman91** [LagoLunatic/wwrando#239]
MS45LjAAd2F4ZWRsaWdodGx5d2VhdGhlcmVkY3V0Y29wcGVyc3RhaXJzAP8PowEPAEADAAAAAAABAAA=

Can't get through the locked door as the Kargarok that normal has the key was the tingle tuner instead.

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
