### ISSUE TITLE
[Question] Private Oasis

### ISSUE THREAD

**Issue by Tmoster02** [LagoLunatic/wwrando#24]
For the sliding puzzle could a item possibly be at the end of all 16 puzzles  the reason why I am asking is because 1 they are annoying 2. I turned off the spoiler log to prevent cheating.

**Comment by JarheadHME** [comment]
No, there's no item at the end of the sliding puzzle, only rupees for completing any and all of them.

**Comment by Tmoster02** [comment]
thanks really did not want to waste time doing all 16
