### ISSUE TITLE
BUG - Can't Progress in DRC. Key in inaccessible location

### ISSUE THREAD

**Issue by chairhome** [LagoLunatic/wwrando#241]
Seed: SuspiciousYoungOutset
Hi, playing through DRC, I used the keys that I was given, opened all available chests, but there is a locked door and no other remaining chests.  The key I seem to be missing is in the Big Key Chest, which is inaccessible from where I am (trying to get through the door to the Bird Nest).

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
