### ISSUE TITLE
Nintendo Gallery question

### ISSUE THREAD

**Issue by NathanEisler** [LagoLunatic/wwrando#243]
I'm new to WW Randomizer. I just wanted to ask: is the Nintendo Gallery completable? Even if I start with DX Picto Box, wouldn't figurines like Tetra be unavailable?

**Comment by OlafurKrH** [comment]
No it's not and why would you do that anyway? as fun as it is for me, it's not meant to be done in the randomizer.

**Comment by NathanEisler** [comment]
I usually like to go for full completion, if I can. I just wanted to know ahead of time so I don't have to waste time with it.
