### ISSUE TITLE
For LagoLunatic

### ISSUE THREAD

**Issue by Bcool14** [LagoLunatic/wwrando#246]
Hello LagoLunatic I am sorry for that spamming. I just needed some help cause i am a newbie with linux and Github and I don't know how to download and use this great wind waker randomizer that you created. Could you please help me?

**Comment by LagoLunatic** [comment]
So the OS you use is linux, not windows? Dunno why it took three tries for you to mention that important detail, but in that case...

There hasn't been an official build for linux or mac offered up until now, so you'd normally run the rando from source instead, as explained at the bottom of the readme.
But starting with the next version there will be a linux build too. You can test a beta of that next version out now if you don't want to run it from source: https://nightly.link/LagoLunatic/wwrando/actions/artifacts/72534987.zip
Note that this isn't the official release, so you can't do races with people using the official 1.9.0 build.

**Comment by Bcool14** [comment]
thanks

**Comment by GB-CG** [comment]
@Bcool14 Please join the discord if you have any more questions: https://discord.gg/r2963mt

**Comment by Bcool14** [comment]
Oh. Ok.
