### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by gwahyzark** [LagoLunatic/wwrando#248]
The randomizer executable for any version I have tried will not launch, and will instead show this:
![image](https://user-images.githubusercontent.com/84997377/129095882-51800bc5-015b-41ef-8419-4f29039ff178.png)
And yes, I have tried both the 64 bit and 32 bit applications. I hope I can get a response soon.

Signed, Gwahyzark

**Comment by LagoLunatic** [comment]
Try adding an exception to your antivirus

**Comment by gwahyzark** [comment]
ok lemme try

**Comment by gwahyzark** [comment]
It did not even launch

**Comment by gwahyzark** [comment]
nvm
thx for responding so quickly
