### ISSUE TITLE
[Suggestion] QoL Improvements without Randomization

### ISSUE THREAD

**Issue by chrisasma103** [LagoLunatic/wwrando#249]
Hi, I don't know if this is a dumb ask, but I'd love to play the game with the QoL improvements without randomizing. I first played this game Wii U, and I'm a little hesistant to go back to the original since I don't own a Wii U anymore. I saw that this randomizer has things like the Swift Sail and faster text speeds (and inverting the camera's x-axis. I tried playing Twilight Princess once on GCN and the camera controls were killing me). I'd love to play the original wind waker with those improvements. Is there any way to? I know that OoT and Majora's Mask got standalone QoL patches from their randomized version AFAIK. It would be really cool to see.

**Comment by LagoLunatic** [comment]
I don't feel like maintaining such an option, you can find an unofficial one here though: https://github.com/WideBoner/betterww
