### ISSUE TITLE
Broken Item Logic ?

### ISSUE THREAD

**Issue by alkaris2** [LagoLunatic/wwrando#250]
I was playing through a rando seed and the item I obtained was a Progressive Bomb Bag, but after obtaining it, I don't actually have the bomb bag, If you picked up a progressive bomb bag it should give you a bomb bag with some in it.

**Comment by wooferzfg** [comment]
This is intended - you need to get the Bombs to be able to actually use them. The Bomb Bag item just increases how many bombs you can carry.
