### ISSUE TITLE
Ganon's Castle softlock

### ISSUE THREAD

**Issue by OSSFrost** [LagoLunatic/wwrando#251]
I believe that entering Ganon's Castle without Boomerang is a softlock unless you know Puppet Ganon skip, as the switches to exit Ganon's Castle turn off too quickly to be possible with bow, and Puppet Ganon can't be killed without Boomerang.

I would suggest either adding a patch to mark the Ganon's Castle exit puzzle as solved, or require Boomerang to enter.

**Comment by JarheadHME** [comment]
You can just leave the same way you came in without any extra items, the boomerang puzzle is just for a shortcut
