### ISSUE TITLE
Randomization failing

### ISSUE THREAD

**Issue by AverageMelon235** [LagoLunatic/wwrando#252]
![image](https://user-images.githubusercontent.com/90166764/132154206-edbb491d-3609-4c49-b842-a5f70933ed42.png)
^this keeps happening every time I try to randomize. I have tried 3 separate ISO file, and none of them have worked. How should I go about fixing it?

**Comment by wooferzfg** [comment]
Try changing your output folder to your `Gamecube Roms` folder? Also consider running the randomizer program as an admin.

**Comment by AverageMelon235** [comment]
now i'm coming across another problem. If I remove the randomizer program from the .zip folder it is in, it no longer will run properly, and i can not run it as admin inside the .zip folder
![image](https://user-images.githubusercontent.com/90166764/132156209-051a3270-c2d9-477b-a13c-a7c1b3b137f1.png)

**Comment by LagoLunatic** [comment]
If it won't run outside a zip folder it's probably just your antivirus detecting it as a false positive. Add an exception for the randomizer or disable your antivirus.
