### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: item_names.txt

### ISSUE THREAD

**Issue by ChazzzyF** [LagoLunatic/wwrando#254]
I just downloaded the 64-bit version of this program to my Windows 10 laptop for the first time and started setting up my first randomizer.
The permalink I ended up getting was "MS45LjAAQmlnQ3Vua2luAJ//KwAOQEADAAAAAAAgAAA=", and I also wrote in a seed name. I also downloaded the custom models and was going to use one. (Unsure if any of this matters, but figured it'd be helpful to provide)
And when I clicked the "Randomize", I got this error.

![image](https://user-images.githubusercontent.com/25673685/132578806-54676985-976c-4373-8a5c-5eb2f0caa069.png)
(Edited to remove my name from it, which is just the user name for my computer)

**Comment by LagoLunatic** [comment]
Unsure what causes it, but other people with that issue said that using the 32 bit version of the randomizer instead of the 64 bit version fixes it.

**Comment by ChazzzyF** [comment]
Ah! That did the trick! Thank you so much!
