### ISSUE TITLE
Freeze after opening chest in randomized The Legend of Pokemon modpack

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [LagoLunatic/wwrando#257]
Hey, when opening the chest in the following screenshots, when link holds the item up, it makes the sound that 1/5/10/20/50 rupees makes, but the texture of the item is blank, and the game freezes after the 'item obtained' audio completes. I am using a pretty recent Dolphin development build (5.0-15158), and no cheats whatsoever. I can reproduce the freeze every time I open the chest, even from a reset. I will also attach my spoiler log.

![image](https://user-images.githubusercontent.com/1993598/135157458-5edff20e-39a3-4b6d-9fac-ae42042209f8.png)

![image](https://user-images.githubusercontent.com/1993598/135157513-5f8150c7-cb8e-4bb2-8731-61c1ac78882b.png)

[WW Random RandomizedPoS - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/7246963/WW.Random.RandomizedPoS.-.Spoiler.Log.txt)

I renamed the .txt file to not use foul language, just so you know. The 'o' in 'of' should be capitalized as well.

**Comment by LagoLunatic** [comment]
I'm not the creator of the Legend of Pokemon mod and don't provide support for it. I recommend checking the mod's readme in case this is a known bug with the pack.
