### ISSUE TITLE
Impossible Seed

### ISSUE THREAD

**Issue by 03bgood** [LagoLunatic/wwrando#258]
[WW Random IntricateGrandRadar - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/7619672/WW.Random.IntricateGrandRadar.-.Spoiler.Log.txt)

Says I have to beat the Savage Labyrinth by reaching level 50 to get the Command Melody, but its not possible with only the Skull Hammer and only 3 hearts! Grapple Hook is in the Earth Temple but I need the Command Melody to progress past the first room. Am I softlocked!? How is this logic allowed?

**Comment by wooferzfg** [comment]
> its not possible with only the Skull Hammer and only 3 hearts

It is possible, but it's really hard. I'd recommend learning the [Soup Glitch](https://youtu.be/RpZJwGAQdtM), or doing some of the non-progress locations to get more hearts.

**Comment by OlafurKrH** [comment]
Oof, RIP dude. Yeah it is possible, but you have to be extremely damn good at the game. I once had to do something similar, but I had about 10 hearts and bottles. Yes, learn the soup glitch, it's a life-saver. Good luck on the darknuts, they'll be the hardest ones to deal with hammer only.
