### ISSUE TITLE
Can't get bombs

### ISSUE THREAD

**Issue by memonster45** [LagoLunatic/wwrando#26]
I gave up and looked at the spoil log, and to get bombs, I need to do Zunari's trade quest. To do that I need the Delivery bag, which is sunken treasure at spectacle island, which is chart 22. But to get chart 22, I need to sink the gunships, at rock spire isle, with bombs. 
Permalink: MS4yLjAAV2Vha0dyYXRlZnVsR2VhcgD///8AAAM=

**Comment by LagoLunatic** [comment]
Look at the charts section of the spoiler log.
```
Charts:
  Triforce Chart 2:  Spectacle Island
```
You don't need chart 22 to get the spectacle island treasure, you need triforce chart 2. Which is the second prize for doing the minigame on spectacle island, coincidentally.
