### ISSUE TITLE
Apparently stuck run?

### ISSUE THREAD

**Issue by HKRARKK** [LagoLunatic/wwrando#261]
I generated a non-spoiler log just to be a full-blind run, but it appears that I'm tried literally anything (as far as I can do), and even did some bugs to reach certain areas to get some items, but to no avail.

The permalink of the run is MS45LjAAaGlrAP//f4IPYEADAAAAAAABAAA= and the seed was "hik"

**Comment by LagoLunatic** [comment]
How far are you in the run? What items do you have?

**Comment by LagoLunatic** [comment]
Or more specifically, what items did you have before you started doing glitches? Since that wasn't necessary to beat the run.

**Comment by HKRARKK** [comment]
> As for now, the items are:

- Full Triforce
- First Sword
- All Orbs
- Mirror Shield
- Boomerang
- Arrows (with Fire and Ice)
- Skull Hammer
- Delivery Bag
- Bait Bag
- One Bottle
[No additional melody besides the starting ones]

The Dungeons discovered but stuck because I don't have some necessary items are: Tower of Gods, Earth Temple and Forbidden Woods

I don't know if I forgot some lookout platform or submarine, but I'm pretty sure I went to every one that I can at least get the chest without bombs.

Still trying this run tho.

**Comment by OlafurKrH** [comment]
You can destroy the cannons on the lookout platform with the boomerang.

**Comment by HKRARKK** [comment]
OH OK. Now I know what I did wrong. Never defeated these cannons with boomerang, just with the bombs above them!

**Comment by HKRARKK** [comment]
Just tested a while now.
Man, how in my 16 years that I know this game I NEVER knew boomerangs could do this?? haha

Anyway, it was a dumb thread after all, but thanks for the help, buds!
