### ISSUE TITLE
Impossible seed?

### ISSUE THREAD

**Issue by jaxad0127** [LagoLunatic/wwrando#266]
A seed I generated (version 1.9.0) seems to be impossible, as it requires `Bombs` to get `Bombs`, specifically `Bombs` are at `Southern Fairy Island Lookout Platform - Destroy the Northwest Cannons`. `Progressive Bomb Bag` does not give `Bombs` (would be nice to merge `Bombs` into `Progressive Bomb Bag`, like other Zelda randomizers).

The generated playthrough also does some things in an impossible order, though this is less of an issue. Specifically, getting these before `Bombs`:
- `Cliff Plateau Isles Highest Isle` (or `Fire Arrows`, which require `Bombs` in this seed)
- `Pawprint Isle Chuchu Cave - Behind Right Boulder`
- `Bomb Island Cave`
- `Eastern Fairy Island Great Fairy`

I've attached the spoiler log.

[WW Random ConvenientCarefulGoal - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/8155683/WW.Random.ConvenientCarefulGoal.-.Spoiler.Log.txt)

**Comment by JarheadHME** [comment]
You can destroy the platform canons with the boomerang as well, which is accessible to you without bombs

As for the other stuff being done without bombs, they all can be accessed with alternate items. Cliff Plateau you can get to by bringing a burning stick with you into the boko baba bulb and then throwing it over at the wooden boards to burn them down. All of the others can be accessed with power bracelets, as they are simply large rocks.

**Comment by jaxad0127** [comment]
I've never heard of those techniques before. You'd think the game would fore you to drop sticks when entering boko baba bulbs, like it does when you try to do anything else while carrying one. I now have bombs and power bracelets, using those strategies.
