### ISSUE TITLE
Impossible seed

### ISSUE THREAD

**Issue by KLPD123** [LagoLunatic/wwrando#268]
I ran the randomizer from source and allowed for obscure things such as "Orca 100 hits" and "Give Mrs. Marie 1-2 Joy pendants" to be randomized and possibly contain necessary items. I did not edit the logic. Basically, I am stuck because i only have 1 bow, and the other two progressive bows are in fire mountain and "Place shop guru statue on arch." When I put the shop guru statue there and talk to the lighthouse guy, he just keeps talking about how he wants the lighthouse to turn on.

I think he will only give you me the bow if the lighthouse is turned on first. Which is impossible because the other bow is in fire mountain. I checked the logic for this check and it along with the other 3 rewards he can give you only have the requirements of "Rescued Aryll" and "Delivery bag."

**Comment by LagoLunatic** [comment]
> I think he will only give you me the bow if the lighthouse is turned on first.

Nope, not required.

> When I put the shop guru statue there and talk to the lighthouse guy, he just keeps talking about how he wants the lighthouse to turn on.

Why are you talking to the lighthouse guy? You have to talk to the guy who stares at the gate. https://zelda.fandom.com/wiki/Kane

**Comment by KLPD123** [comment]
Omg I thought Kane was the lighthouse guy! I don't know why I remembered him being the one to give you the arch rewards. I've played this game hundreds of times and I still learn new things. Thank you!
