### ISSUE TITLE
Savage Labyrinth Hint Tablet Item Message

### ISSUE THREAD

**Issue by Dev5ter** [LagoLunatic/wwrando#27]
I have the newest version of the randomizer. I know this because I can change character models, and their hair/clothes color. If I'm assuming correctly, the tablet under the giant head, and right next to the secret cave is supposed to have the information on what items are on floors 30 and 50. It says "The Savage Labyrinth! Deep in the never-ending darkness, the way to challenge awaits". Does this mean I'm looking at the wrong tablet, it only shows progression items on the tablet if there is any, or mine is possibly bugged? Thanks in Advance!

**Comment by LagoLunatic** [comment]
Only shows progression items - non-progress items always show up as "challenge" in regular color text, while progress items have item-specific hints in orange text.
