### ISSUE TITLE
Invalid write to 0x01234567, PC = 0x80006d64 

### ISSUE THREAD

**Issue by AdetFearwhale** [LagoLunatic/wwrando#273]
Game crashes during Pompie and Vera Secret Meeting Photo Quest, they gave a Triforce Shard so I cannot complete the run. Error screen "Invalid write to 0x01234567, PC = 0x80006d64" appears and the game stops.

**Comment by LagoLunatic** [comment]
Post information about what Dolphin version you're using, what randomizer version you're using, what cheat codes you have enabled, and what other wind waker mods you have enabled besides the randomizer itself.

**Comment by AdetFearwhale** [comment]
Dolphin 5.0-16101
Randomizer 1.9.0
Cheat Codes:
![image](https://user-images.githubusercontent.com/105134861/167284915-6b32d601-5e56-4081-8a1f-21f9a601395f.png)

Other Mods:
Player Model Linka
The Legend of Pokémon

**Comment by LagoLunatic** [comment]
> Cheat Codes:

Those aren't cheat codes, those are the normal randomizer settings.

> The Legend of Pokémon

I've heard of this mod causing crashes before, so that's the cause of it. Not the randomizer. Check the mod's readme to see if it has any tips for fixing crashes.
