### ISSUE TITLE
Stuck 

### ISSUE THREAD

**Issue by link2231** [LagoLunatic/wwrando#281]
Nauru’s pearl has spawned in the master sword chamber 
Seed: HorizontalUniformMothula
If there’s a way to still finish the game I’d love to know

**Comment by wooferzfg** [comment]
The warp to Hyrule appears once you have the Triforce, even if you haven't raised Tower of the Gods yet.

**Comment by link2231** [comment]
Yup that did the trick thanks, didn’t know that !
