### ISSUE TITLE
Bug Baito

### ISSUE THREAD

**Issue by TristanVLM** [LagoLunatic/wwrando#285]
I can't do Rito Aerie - Baito because he doesn't want to go inside Dragon Roost Island and I looked in the spoiler log, he has to give me the last Triforce Shard I need. If someone can tell me what triggers him, it will be very helpful.

**Comment by LagoLunatic** [comment]
You need to do the letter sorting minigame 4 times. get a score of 10, then 20, then 25, then reload and Baito will be there. Then get 25 again.
