### ISSUE TITLE
Unobtainable Bombs

### ISSUE THREAD

**Issue by JayBirdGuru** [LagoLunatic/wwrando#29]
I spent many hours trying to locate Bombs without success, so I consulted the spoiler log.  According to the log, the bombs are given by the Great Fairy on Eastern Fairy Island.  But I can't enter the island without bombs - unless I'm completely missing something.

My seed is BrilliantFeebleFool.

**Comment by LagoLunatic** [comment]
Power bracelets let you lift and throw boulders

**Comment by JayBirdGuru** [comment]
Ah.  Learn something new every day.  Thanks!
