### ISSUE TITLE
Make Medli or Makar as a partner outside the wind or earth temples?

### ISSUE THREAD

**Issue by talesono12** [LagoLunatic/wwrando#291]
Hello Is it possible to use medli or makar as a partner outside the Wind and Earth temples. It would be great to have the player control the partner like for example medli flies and gets a key in a different dungeon if that is even possible to happen.

Thanks.

**Comment by LagoLunatic** [comment]
Not easily. You'd have to recode how Medli and Makar work to let them work in other stages, and probably update lots of the stages themselves to accommodate them better. e.g. There are memory concerns with Medli and Makar being in other stages that already use most of the GameCube's memory.
