### ISSUE TITLE
Quest Items

### ISSUE THREAD

**Issue by Izabelle92** [LagoLunatic/wwrando#292]
Hi!
I have a small problem with the randomizer program. Just about everything works and the program itself is up to date.
However, when I play a randomized seed the quest items don't work nor show up in my inventory. I had got a seed where
the Cabana secret is the bomb island entrance. I got the Cabana deed from the Forsaken Fortress cell and even did the quest for Ms. Marie just to verify the quest activation and yet I am still unable to enter the Cabana at all. Other quest items don't seem to work either.
I literally can't beat this swordless run because a progressive bow is in the Cabana, and the last progressive bow is after the darknuts on Totg. To my knowledge darknuts are impossible to defeat on swordless without light arrows.

**Comment by LagoLunatic** [comment]
> I have a small problem with the randomizer program. Just about everything works and the program itself is up to date.
> However, when I play a randomized seed the quest items don't work nor show up in my inventory. I had got a seed where
> the Cabana secret is the bomb island entrance. I got the Cabana deed from the Forsaken Fortress cell and even did the quest for Ms. Marie just to verify the quest activation and yet I am still unable to enter the Cabana at all. Other quest items don't seem to work either.

I'm not sure what you mean by "quest items", but in order to use the cabana deed you must first find the delivery bag.

> darknuts are impossible to defeat on swordless without light arrows.

Skull hammer

**Comment by Izabelle92** [comment]
Skull hammer works?
I didn't try that. I only say that because I've seen several videos on people doing rando's on Youtube and everyone says light arrows. I tried fighting darknuts in the wizzrobe combat dungeon and couldn't even get behind them to try that.

It will be hard but I guess I will have to try that. Thank you Lago.

(Windwaker is my least played Zelda btw, so I have very little knowledge of this game. Probably shouldn't have done a kaizomizer for it lol.)
