### ISSUE TITLE
Softlock (i think?) in my rando seed

### ISSUE THREAD

**Issue by bizzburnley** [LagoLunatic/wwrando#297]
Hi there,

I am not sure 100% but I think i got into a softlock. 

In order to get the items bombs or grappling hook I would need one of each. 
So in order to get any of the three bomb spot -> grappling hook.
In order to get grappling hook -> I need bombs. 

So I am unable to progress in the game. 

[WW Random SenselessComplimentaryMass - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/9690578/WW.Random.SenselessComplimentaryMass.-.Spoiler.Log.txt)

Sorry if I am wrong with this and I overlooked something, but it seems like it's unbeatable?

**Comment by RealLarsP** [comment]
you dont need grappling hook for bombs. collect the triforce shards and the light leading to hyrule is there. you dont need to finish the tower for hyrule-access

**Comment by RealLarsP** [comment]
(also its a better idea to ask in our discord server instead of opening an actual issue lol)

**Comment by bizzburnley** [comment]
Hi, i am in the discord and I figured, since I thought I got softlocked or there was an logic issue, better make a ticket. Just as described in the #bug-reports channel. *lol*

Thanks for the help and again, sorry, I overlooked something.
