### ISSUE TITLE
Invalid Read from: 

### ISSUE THREAD

**Issue by zeldaking** [LagoLunatic/wwrando#298]
When I launch Dolphin with both regular wind waker or rando wind waker I get an error saying: Invalid Read from (Number Random Each Time), PC = (Number Random Each Time) and later it says: An error occured. IntCPU Uknown Instruction (Random Number) at PC  = (Random Number), last_PC = (Random Number) LR = (Random Number) Condition 0 File d:/Source/Core/Core/PowerPC/Interpreter/Interpreter.cpp Line: 343 Function: unknown_instruction and then it crashes.

**Comment by LagoLunatic** [comment]
Not an issue with the randomizer since you said it happens with regular WW too. Mess with your dolphin settings.

**Comment by zeldaking** [comment]
Nvm I figured it out. I had a bad dump. I re-dumped the game and it worked after that.
