### ISSUE TITLE
Models No Longer Selectable

### ISSUE THREAD

**Issue by bluedart** [LagoLunatic/wwrando#299]
I just downloaded and ran the latest version from source, and downloaded the model pack listed [here](https://github.com/Sage-of-Mirrors/Custom-Wind-Waker-Player-Models).  The only issue I'm having is that it won't recognize or allow me to choose any custom models in the Player Customization tab.  The models are in the same sub-folder and structure as the 1.9.0 release I had used previously.  Removing the files and using the "Install a Custom Model or Model Pack" button gives the response "52 models installed successfully", but still does not allow choosing of a player model in the GUI or in the settings file—which defaults back to Link when the program runs again.

When installing models with this button, the cmd output is "Cannot find value Agent 9 in combobox custom_player_model" (or whatever model happens to be alphabetically first in the pack) if that helps.  The outcome is also the same when run from an administrator command prompt using "py -3.10 wwrando.py".

**Comment by LagoLunatic** [comment]
What operating system?

**Comment by bluedart** [comment]
Windows 10 64 bit.

**Comment by LagoLunatic** [comment]
Same and I have no problem installing models, either running from source or with the exe build.

Maybe you don't have permissions to modify the models folder so it can't place them anywhere. What path have you placed the randomizer's folder at?

**Comment by bluedart** [comment]
On a secondary drive.  Forgot to mention I was running cmd in Admin mode just in case.

**Comment by LagoLunatic** [comment]
What happens if you run the command `py -3.10`, and then paste the following code into the command prompt and hit enter:
```py
import customizer
customizer.get_all_custom_model_names()
```
Screenshot or copy paste the command prompt output here.

**Comment by bluedart** [comment]
![console_output](https://user-images.githubusercontent.com/5490843/196312183-8d0f60d6-cd72-47cb-ac10-13c7efd59698.jpg)
Here's something weird.  I copied the whole folder onto my desktop, ran "py -3.10 wwrando.py" from an admin cmd, and the list populated properly.  Running the .py file directly from here also works without an issue.  The problem folder is under the same directory that the 1.9.0 release is, which works properly there.  Why would this make a difference?

(Running the customizer function in my desktop folder gives a proper array of the names, as well.)

**Comment by LagoLunatic** [comment]
Fixed, it was the square brackets in `[Emus]`. Apparently those are special characters to glob.

Didn't affect 1.9.0 since it used relative paths instead of absolute.

**Comment by bluedart** [comment]
Thanks for taking the time to look into this.  I appreciate it.  Have a nice day!
