### ISSUE TITLE
Pictograph Box softlock

### ISSUE THREAD

**Issue by fkhjfhjsfv** [LagoLunatic/wwrando#3]
Taking a picture softlocks the game and I was left with "You can record three more pictographs" text.

**Comment by LagoLunatic** [comment]
How does it softlock? Does it successfully take the picture but not let you back out of the menu after?
Where were you and what were you taking a picture of?
And what's the permalink for the seed?

**Comment by fkhjfhjsfv** [comment]
Permalink: MS4wLjAAQXBwYXJlbnRIb3RHbG9vbQAGDg8IAA==
Pictograph Box came from the Rito who you give 20 feathers to.

Lens of the picto box stayed close after a snap and didn't successfully take the picture. Left unable to do anything.
I was a tile south of Windfall Island. I was in a hurry to take a picture of the moon when the night was almost over. Daytime music began to play during the softlock.

**Comment by fkhjfhjsfv** [comment]
Possibly a fluke that could happen in vanilla. I tried the Picto Box again and no issues.
