### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by Beltice** [LagoLunatic/wwrando#303]
I am trying to launch the Wind Waker randomizer on my computer and I keep receiving the message that I could not run the wwrando script.  Has anyone come across this issue before?

**Comment by LagoLunatic** [comment]
Yes, from the readme:
>Randomizer won't launch?
>If the randomizer gives an error saying "Failed to execute script wwrando", or if the executable disappears before you can launch it, then your antivirus software may be incorrectly detecting the randomizer as malware. You should add an exception/exclusion for the randomizer into your antivirus software so that it will ignore the randomizer if this happens.
