### ISSUE TITLE
Graphical 'status bar' at the bottom of the screen

### ISSUE THREAD

**Issue by ancarda** [LagoLunatic/wwrando#306]
The randomizer produced a ROM that seems to have a 'status bar' of some kind at the bottom:

<img width="752" alt="Screen Shot 2022-12-04 at 3 08 31 PM" src="https://user-images.githubusercontent.com/3399778/205498581-400cd204-6617-45f3-ac57-8e7a4fe49e48.png">

It's visible pretty much as soon as the game boots, but does not happen on vanilla or any other GameCube game. So I don't think Dolphin is to blame:

<img width="752" alt="Screen Shot 2022-12-04 at 3 11 46 PM" src="https://user-images.githubusercontent.com/3399778/205498684-077c1c38-8cf0-4404-b92f-db633418caf9.png">

Is this because I built wwrando from source? Is there any way to disable this? This happens both on 1.9.0 (13ac6ae226a3b4bb69689829356ac8d7a308d0b5) and master (5a9884c537a9d50eb940b64dd95abc195207e905). I don't have a Windows machine handy to run the binaries provided, and they don't seem to be able to run through Wine 😞

* Emulator: Dolphin 5.0.4 (via OpenEmu 2.3.3) on macOS 12.6.1

**Comment by LagoLunatic** [comment]
That's the performance profiling debug UI. It only appears when the game is in developer mode and when a controller is plugged into slot 3.

Either unplug the controller from slot 3, [run an official build from here](https://nightly.link/LagoLunatic/wwrando/workflows/python-app/master), or run it from source but remove the code that enables developer mode.
