### ISSUE TITLE
[Bug] Impossible to complete Seed due to needing the Master Sword to get the Master Sword

### ISSUE THREAD

**Issue by 283leis** [LagoLunatic/wwrando#311]
Wind Waker Randomizer Version 1.9.0
Permalink: MS45LjAATWFydmVsb3VzUGh5c2ljYWxEYXJrbnV0AN//e4AOUEADAAAAAAABAAA=
Seed: MarvelousPhysicalDarknut
Options selected:
  progression_dungeons, progression_great_fairies, progression_puzzle_secret_caves, progression_combat_secret_caves, progression_short_sidequests, progression_spoils_trading, progression_minigames, progression_free_gifts, progression_mail, progression_platforms_rafts, progression_submarines, progression_eye_reef_chests, progression_big_octos_gunboats, progression_triforce_charts, progression_treasure_charts, progression_expensive_purchases, progression_misc, progression_battlesquid, progression_savage_labyrinth, progression_island_puzzles, keylunacy, randomize_entrances: Disabled, randomize_charts, swift_sail, instant_text_boxes, reveal_full_sea_chart, num_starting_triforce_shards: 0, add_shortcut_warps_between_dungeons, sword_mode: No Starting Sword, skip_rematch_bosses, num_race_mode_dungeons: 4, remove_title_and_ending_videos, custom_player_model: Ganondorf, custom_color_preset: Custom, starting_gear: ['Progressive Shield'], custom_colors: OrderedDict([('Eyes - iris', [225, 20, 20])])

Two progressive sword upgrades require the Deku Leaf. The Deku Leaf requires the Spoils Bag, which is in Forsaken Fortress, for which you need the Master Sword (upgrade #2) to defeat Phantom Ganon. A third progressive sword upgrade is in the Earth Temple, and the song to enter it is in the Forbidden Woods (which requires the Deku Leaf!). The last progressive sword upgrade requires you to be able to decipher Triforce Shard maps.

Literally every progressive sword upgrade is locked behind an item that can only be reached once you already have the second sword upgrade, making the seed impossible to complete.

**Comment by LagoLunatic** [comment]
You don't need to defeat Phantom Ganon to get items from Forsaken Fortress. Only for the chest he's guarding, which doesn't have anything worthwhile on your seed.

**Comment by 283leis** [comment]
You need to defeat Phantom Ganon to get into Forsaken Fortress without
glitches.

**Comment by LagoLunatic** [comment]
No you don't, you just need the Skull Hammer to get inside it. In the vanilla game that means you need to defeat Phantom Ganon because he guards the Skull Hammer. But this is a randomizer you're playing. Just get the Skull Hammer where it was randomized to.
