### ISSUE TITLE
Small Key in Dragon Roost replaced by Cabana Deed

### ISSUE THREAD

**Issue by Insomnatrix** [LagoLunatic/wwrando#313]
The Small Key in the bird's nest in Dragon Roost cavern was replaced by the Cabana Deed, making it impossible to progress despite the Key-Lunacy option being disabled. Checking the spoiler log revealed that said key was in the big chest much later in the dungeon.

Here's the full manifest for Dragon Roost Cavern:
    First Room:                                          DRC Small Key
    Alcove With Water Jugs:                              DRC Small Key
    Boarded Up Chest:                                    Triforce Shard 7
    Chest Across Lava Pit:                               DRC Compass
    Rat Room:                                            Piece of Heart
    Rat Room Boarded Up Chest:                           DRC Small Key
    Bird's Nest:                                         Cabana Deed
    Dark Room:                                           Triforce Chart 1
    Tingle Chest in Hub Room:                            Green Rupee
    Pot Room Chest:                                      Piece of Heart
    Mini-Boss:                                           Piece of Heart
    Under Rope Bridge:                                   DRC Big Key
    Tingle Statue Chest:                                 Silver Rupee
    Big Key Chest:                                       DRC Small Key
    Boss Stairs Right Chest:                             Deku Leaf
    Boss Stairs Left Chest:                              Command Melody
    Gohma Heart Container:                               DRC Dungeon Map

EXTRA DETAILS, IF NECESSARY
Permalink: MS4xMC4wAFRpcmVsZXNzRXh0cmF2YWdhbnRMYW5kbHViYmVyAAcBAwAMoL4DANAAAgAAAAABgCAAAA==
Seed Hash: Ankle Kane
Seed: TirelessExtravagantLandlubber

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.
You can reach it with ice arrows: https://imgur.com/R0cYujl
This doesn't apply to this particular seed considering where deku leaf is, but in other seeds you can also reach it with deku leaf: https://imgur.com/jOEq6mx

**Comment by Insomnatrix** [comment]
Oh, I see! Thank you!
