### ISSUE TITLE
Randomizer crashes on start - Qt Platform Plugin Error 

### ISSUE THREAD

**Issue by Daddu3** [LagoLunatic/wwrando#315]
Wondering if this is because I'm using a Windows 8.1-system instead of 10/11, but I'm getting this error upon launching the 1.1.0 randomizer:

![image](https://user-images.githubusercontent.com/53014019/211308306-5521f4cf-16a1-48d0-9636-731d33e3ba87.png)

Previous versions work fine however.

**Comment by LagoLunatic** [comment]
Yeah, it seems Windows 7 and 8 are no longer working with the latest version because the GUI library I use doesn't support them anymore. Win10+/Mac/Linux work.
At some point I'll look into whether it's possible to swap the library version out depending on the OS so they can still be supported.

**Comment by LagoLunatic** [comment]
Windows 8.1 is supported again in the next version. Also in the dev builds, "windows-qt5" link here: https://nightly.link/LagoLunatic/wwrando/workflows/python-app/master
