### ISSUE TITLE
Lookout Platforms Progression Items bug; bombs locked

### ISSUE THREAD

**Issue by jackreever** [LagoLunatic/wwrando#320]
I ran a randomizer where the bombs were locked behind the Fire Mountain lookout platform chest, where I had to destroy the cannons to get the bombs. I don't think it's possible to destroy the cannons without bombs, maybe I'm wrong? 
[WW Random CrazyBriefRoom - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/10698962/WW.Random.CrazyBriefRoom.-.Spoiler.Log.txt)

**Comment by GriffinG1** [comment]
You can destroy the cannons with the boomerang
