### ISSUE TITLE
[Suggestion] Option to Freeze Time Flow

### ISSUE THREAD

**Issue by RecursiveVision** [LagoLunatic/wwrando#326]
I thought about my weather-related suggestion to remove storms, but ultimately that would be niche and probably not worth the effort, so I closed that issue (although by all means reopen it if you want to program it).

Here is a suggestion that I think a lot more people would use: an option to freeze the flow of time, so that it's always day or always night (unless the Song of Passing is played).

The reason I think this would be appealing is that the music only plays in outdoor regions during the day, and visibility is increased during the day.

I believe this might also remove storms, since during the initial sail to Dragon Roost Island when time is frozen, the weather is never stormy, indicating that storms aside from those generated by cyclones/Big Octos are related to time flowing. This could be a special flag, though (if it is, the option to remove storms suddenly becomes a lot more feasible to program).

Challenges: This would require changing the logic such that items which must be obtained during a specific time of day (most of the Windfall Island quests, Spectacle Island prizes, Mesa's house on Outset, the Ghost Ship, the Blue ChuChu on Horseshoe Island which only appears at night) appear after the Song of Passing is obtainable. This would also make the Song of Passing more useful, which is kind of cool.

After clearing the Ghost Ship, the time is set to dawn, which would lock out any night-related quests.

In addition, the Forsaken Fortress changes time to night upon visiting there. This can be handled in a number of ways:
- The eternal night curse could be removed (by default or as an option); might not be feasible with Helmaroc King fight graphics and/or game crashes
- Code could be added to change time back to day upon leaving the Forsaken Fortress, if time flow was frozen and it was previously daytime (might not be feasible if that can't be stored in memory)
- All progress items could be obtainable at night if the option to freeze time flow is enabled
- All progress items obtainable from daytime only quests could require the Song of Passing to be obtainable earlier in the logic

**Comment by LagoLunatic** [comment]
Seems useless and a lot of effort, doubt anyone would be interested in using this or coding it
