### ISSUE TITLE
[Suggestion] FF3 Map After Helmaroc King & Phantom Ganon Defeat

### ISSUE THREAD

**Issue by RecursiveVision** [LagoLunatic/wwrando#327]
After defeating both the Helmaroc King and Puppet Ganon, it would be nice if the FF3 map was loaded (searchlights disabled and such) and the eternal night curse dispelled.

The current situation where it remains in its FF2 state for the whole game, despite the Tower of the Gods' appearance, the Greatfish Isle cloud disappearing as progress is made, and the portal opening from Ganon's Tower, feels a bit immersion-breaking to me.

**Comment by LagoLunatic** [comment]
The door into Helmaroc's boss room gets covered in rubble and blocked off in FF3, which means you can't go back and pick up the dropped item if you missed it. I assume there would be other issues too but I don't feel like testing it.

There's no point to this change so it would be a waste of effort to fix the problems. And preserving immersion isn't the point of the randomizer. I intentionally did things like this to keep the game in an open world state permanently.
