### ISSUE TITLE
Randomizer crashes when starting with every item

### ISSUE THREAD

**Issue by RecursiveVision** [LagoLunatic/wwrando#329]
![bd25a6dd56101dd54ef0dc0f6167fd40](https://user-images.githubusercontent.com/66801010/219882153-83a1fd1c-17d9-497e-830a-cde2ea0bc99f.png)

Running the randomizer from source. Every item in the Starting Items tab was given.

**Comment by LagoLunatic** [comment]
This seems to be because the Big Octo Great Fairy always gives a random item hint, even if you say you want zero item hints.
But I already fixed this prior to releasing 1.10.0: c67a0eaa16c164d7441908ed8bd88489eee1f514
Not sure how it reappeared.

**Comment by wooferzfg** [comment]
There's some progress items you can't start with (e.g. Tingle Statues). Could it be related to that?

**Comment by LagoLunatic** [comment]
This only happens when progression Dungeons are enabled (causing keys to be counted as progress items that you don't start with) and Key-Lunacy is disabled (causing keys to not be hintable).
