### ISSUE TITLE
Randomizer crashes if 0 progress locations are chosen, even if all progress items are given

### ISSUE THREAD

**Issue by RecursiveVision** [LagoLunatic/wwrando#330]
![79dea32200f21d21e5c501aac53602bd](https://user-images.githubusercontent.com/66801010/219882228-b1245972-5f2a-4cfe-9d66-4f6dddf0c713.png)
Running the randomizer from source. All items were given under Starting Items.

**Comment by LagoLunatic** [comment]
This seems to be because the Big Octo Great Fairy always gives a random item hint, even if you say you want zero item hints.
But I already fixed this prior to releasing 1.10.0: c67a0eaa16c164d7441908ed8bd88489eee1f514
Not sure how it reappeared.
