### ISSUE TITLE
Add a "Save" button for custom color on skin page

### ISSUE THREAD

**Issue by kenokeefe91** [LagoLunatic/wwrando#333]
Here is the thing.

I really love my colored link, but sometime I like to change it for another skin (yeah strange I know)

Problem doing this is, I lost my custom colors on my customized link :(

Would it be possible to have a save button on skin page with a texbox near it so I can save my current custom under a specific name and reuse it later ?

Thanks

**Comment by LagoLunatic** [comment]
The next version allows you to save color presets to a file and load them later.
