### ISSUE TITLE
Cyclos: Unreasonable Window of Time

### ISSUE THREAD

**Issue by RecursiveVision** [LagoLunatic/wwrando#335]
Running the randomizer from source using the following settings: MS4xMC4wXzhhZTJiY2EARml2ZUFsZXJ0TGluawAHAQMADqC+AwTQAAIAAAAAASAVAAA=

From my observations in vanilla, Cyclos has two "modes" based on event flags. The first mode occurs when you approach him after obtaining Farore's Pearl, thus unlocking access to the ocean. During this mode, you're assumed to not be able to defeat him yet, so the cyclone sucks you up very quickly and sends you elsewhere.

The second mode occurs - not after obtaining the Hero's Bow as you'd expect - but caused by an event flag sometime after clearing Tower of the Gods. In this second mode, you have more time before the cyclone sucks you up, making it easier to get three hits on Cyclos.

I started with the Hero's Bow and 99 arrows and went immediately towards the Shark Island cyclone, but found Cyclos to be in the first mode and was unable to defeat him as a result, although in fairness I was not trying to as I just wanted to get the pictograph, and didn't fire any arrows.

(Note: It is still possible to defeat him - I have done it before - and it functions the same if you do succeed, but it's significantly more difficult.)

**Comment by LagoLunatic** [comment]
Are you sure this is real? None of the flag checks in Cyclos' code look like they could be for this.

In my experience, it seems like Cyclos sucks you up in around 5 seconds if you don't take the bow out, or in around 25 seconds if you take the bow out but don't kill him in time. Could this be what you're thinking of?
