### ISSUE TITLE
[Request] Add archipelago support

### ISSUE THREAD

**Issue by vekk513** [LagoLunatic/wwrando#339]
Support for [archipelago multiworld randomizer](https://github.com/ArchipelagoMW/Archipelago) would be awesome! 

Not sure if this has been looked into already but would love to see WW in there to play.

**Comment by Crain-32** [comment]
I'm working on the Multiworld project, currently have no interest in integrating with Archipelago. Someone can use my code to do so once I'm done.

**Comment by LagoLunatic** [comment]
I won't do this but if someone else wants to add WW support for archipelago with wwrando's code as a base they're free to do so.
