### ISSUE TITLE
Can't get Nayru's Pearl

### ISSUE THREAD

**Issue by TwagginWagon** [LagoLunatic/wwrando#34]
Looked at the spoiler log for Nayru's Pearl, and it says its located in the Maze chest in Ganon's Tower. I have all Triforce pieces, but as far as I'm aware you can't get to Ganon's tower without first opening up the tower of the gods to get to Hyrule. Is there a way to get there I'm unaware of?

My seed is TreacherousSavingMedli

**Comment by OlafurKrH** [comment]
You actually can get to Hyrule without the three pearls. its just Tower of Gods you cant enter.

**Comment by TwagginWagon** [comment]
Are there any steps besides getting all Triforce pieces to open the portal then? I'm looking around the Tower of the Gods area, but there doesn't seem to be any portal showing up.

**Comment by OlafurKrH** [comment]
Light Arrows and fully powered Master Sword I'm sure.

**Comment by TwagginWagon** [comment]
Yep, that's the issue, didn't know you needed those. Thank you!
