### ISSUE TITLE
The File is Being identified as malware

### ISSUE THREAD

**Issue by KingDeku86** [LagoLunatic/wwrando#340]
What is happening is when i try to download the file, my antivirus identifies the file as malware. When I downloaded it on my phone and sent it through dropbox, i was able to get the zip on my computer but then the main .exe was being put into the quarentine. please look into this it would be much appreciated!

**Comment by LagoLunatic** [comment]
That's normal. I don't have control over what programs the antivirus randomly detects as false positives. Add an exception for the randomizer into your antivirus software, or disable it entirely.
