### ISSUE TITLE
When playing with Item/Path hints & Key-Lunacy, prevent non-required keys from being hinted as if they were progression items.

### ISSUE THREAD

**Issue by Ganaham** [LagoLunatic/wwrando#342]
I realize this might be less tied to the hints and more to how Key-Lunacy logic operates, so an idea for a band-aid could be a disclaimer about this in either the Key-Sanity or hints tooltips.

**Comment by wooferzfg** [comment]
This is how Item hints currently work in general - they'll hint at progress items even if those items aren't required to beat the game. The keys work the same way
