### ISSUE TITLE
Unsolvable Seed

### ISSUE THREAD

**Issue by saiyaruki** [LagoLunatic/wwrando#347]
Was about 10+ hours into a seed only to find myself stuck due to blue chu jelly quest locking out the hookshot. You cannot obtain the blue chu jelly on Overlook Island without hookshot at least glitchless (as far as I know). 

Attatched is my spoiler log for the run.

[WW Random ThreeDistinguishedNohansen - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/12520528/WW.Random.ThreeDistinguishedNohansen.-.Spoiler.Log.txt)

**Comment by TwistedAkai** [comment]
There's 23 blue chus and you only need 15 jelly.

**Comment by LagoLunatic** [comment]
14 have no requirements, only a couple of the remaining 9 require hookshot. The blue chu on Horseshoe island should be doable with Deku Leaf

**Comment by saiyaruki** [comment]
Ah my bad thought there were only 15
