### ISSUE TITLE
Randomizer failed with error: No useful progress items to place!

### ISSUE THREAD

**Issue by Sirius902** [LagoLunatic/wwrando#35]
Title says it all. Error log is included.
[WW Random ThoughtlessSuccessfulBeedle - Error Log.txt](https://github.com/LagoLunatic/wwrando/files/2344238/WW.Random.ThoughtlessSuccessfulBeedle.-.Error.Log.txt)

**Comment by LagoLunatic** [comment]
Fixed in f55a47a7a3672ce3e58fd53bfdbb1ecafa6cf42d
