### ISSUE TITLE
Stuck in seed, Beedle's Shop Ship 20 Rupee item not what progression log claims

### ISSUE THREAD

**Issue by SilverEye91** [LagoLunatic/wwrando#352]
Seed: LeadingFrigidBombchu

I got severely stuck in the randomizer and decided to use the spoiler log, that claims the 20 rupee item in Beedle's shop ship is the bombs. However, all Beedle has to sell are arrows (which I can't buy because I don't have a bow) and bait.

**Comment by wooferzfg** [comment]
Beedle only sells the 20 rupee item at some islands - Spectacle Island, Pawprint Isle, Dragon Roost Island, Eastern Triangle Isle, Southern Triangle Isle, Forest Haven, and Outset Island.

**Comment by SilverEye91** [comment]
Oooohhh! That's a great map! I figured it was something like that, but searching for it online I didn't actually find anything. But that's a good map! Thanks!
