### ISSUE TITLE
Wind Waker Randomization Error

### ISSUE THREAD

**Issue by ShuppetChair** [LagoLunatic/wwrando#355]
I Have a Clean Install of WW but when I put it into the program It says "Invalid game given as the clean ISO. You must specify a Wind Waker ISO (USA version)" I don't know how to "specify a Wind Waker ISO" Can someone help me please I am on Windows 11 with version 1.10.0 of the Randomization software.

**Comment by mathgirl718** [comment]
You'll need a legally dumped copy of wind waker (the usa version is the only one that works). Under randomizer settings, Clean WW ISO you'll need to browse your computer to locate the dumped iso.

**Comment by ShuppetChair** [comment]
Ok thank you for the clear response everywhere else it looks like gobbly gook.
