### ISSUE TITLE
Problem running TWW Randomizer 1.10.0 on Windows 7

### ISSUE THREAD

**Issue by GeniusKoala** [LagoLunatic/wwrando#359]
Hello,

I currently have a problem when trying to use the recently released TWW Randomizer 1.10.0 (GUI version) on my Windows 7 laptop (SP1 64 bits). I get an error message saying it's trying to find a "**_python310.dll_**" and then it doesn't run the program.

I never had any issue prior to TWW Randomizer 1.10.0.
I have Python 3.8 installed (last Windows 7 supported version) but it's for OoT Randomizer and I don't recall TWW Randomizer requiring Python to be installed for the GUI (at least it doesn't seem to be mentioned in the readme aside for building from source).

So, as I didn't know what to do, I tried installing a rebuilt Python 3.10 for Windows 7 through https://github.com/adang1345/PythonWin7
Unfortunately, it still won't work but it gives me another error:

```
Failed to execute script 'wwrando' due to unhandled exception:
DLL load failed while importing QtGui: The specified procedure could not be found.
Traceback (most recent call last):
  File "wwrando.py", line 3, in <module>
ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.
```

I made an exception for it in my antivirus and I also tried with the antivirus disabled but the result is the same.
May someone help me solving this issue, as I have not a single idea as where the problem comes from?

Thanks in advance.

**Comment by LagoLunatic** [comment]
For version 1.10 of the randomizer I had to upgrade to newer versions of Python an Qt (Qt is the GUI library I use). Windows 7 and 8 are both no longer supported by Microsoft, so Python dropped support for Windows 7, and Qt dropped support for both Windows 7 and 8. So neither of those operating systems can run 1.10 of the randomizer.

It might be possible for me to have the randomizer support multiple versions of Qt, so that depending on the user's operating system it either uses a new version of Qt or an old one, and if this was done it may work on Windows 7/8. I haven't gotten around to looking into this yet though.

**Comment by GeniusKoala** [comment]
Thank you for your answer.

I had a feeling it was something related to using obsolete Windows versions and it happened to be it (unfortunately, I can't afford a new computer).
That said, if a workaround is possible, like you mentioned, that's good news but don't feel forced to implement it if you think it's not worth it. I don't know anything about Python so I'd feel bad wasting your time for nothing.

As for myself, I can keep using TWW Randomizer 1.9.0 or I'll try to run 1.10.0 with other tools (Virtual machine if it runs on my potato laptop or Linux live USB).

Anyway, thanks again for your help!

**Comment by LagoLunatic** [comment]
Latest commit from source now supports both Qt 5 and Qt 6 simultaneously. So if you install Python from that PythonWin7 link, and then run the randomizer from source, but install of installing `requirements.txt` you replace it with `requirements_qt5.txt`, the randomizer should now run under Windows 7 with Qt 5 properly.
