### ISSUE TITLE
short and long quest tweaks suggestion

### ISSUE THREAD

**Issue by Metalelite54** [LagoLunatic/wwrando#363]
Hi everyone. this is the first time I write something on github and i'm not into coding.

All I know is on some hardware there is issues with dolphin regarding the pictobox image compression
<img width="923" alt="bug dolphin" src="https://github.com/LagoLunatic/wwrando/assets/49573756/fc77c416-a003-444b-8a45-4d0d5719aa52">
<img width="958" alt="bug dolphin2" src="https://github.com/LagoLunatic/wwrando/assets/49573756/5e79bae0-875a-4ff1-9392-041aec0679da">

i've tried many tweaks on the dolphin emu and it didn't work.

so what I propose is instead

would it be possible to tweak the short and long sidequest option to be able to enable or disable each quest.

for example. 
enable joy pendant quest but disable deluxe pictograph sidequest

or like disable decorating town but activate zonari's trade quest.

Sorry if this is in the wrong section I don't know how this website works.

**Comment by LagoLunatic** [comment]
Not a bug. Dolphin increased internal resolution hack doesn't work with pictures taken by the pictobox. Those pictures are actually saved as pixels inside your save file, so increasing the resolution of the pictographs is impossible as it would take up more space on the memory card. So your hardware doesn't matter, they always work as they originally did as if you were actually playing on a GameCube and not dolphin no matter what.

> would it be possible to tweak the short and long sidequest option to be able to enable or disable each quest.

Not sure what this has to do with the pictographs not being affected by increased internal resolution. But either way I don't plan on adding this.
