### ISSUE TITLE
Impossible Broken Seed

### ISSUE THREAD

**Issue by Quades1** [LagoLunatic/wwrando#365]
I have encountered a seed where essentially the Skull Hammer is located under tower of the gods in the master sword room. The issue with that is, one of the pearls necessary for getting to Tower of the Gods is located in the bottom jail within forsaken fortress which requires the hammer to access... Therefore, without finding a way to glitch my way through forsaken fortress hammer spike things, this playthrough is impossible. 

Permalink:

MS4xMC4wAFdvcnJpc29tZVNhbHR5U3F1YXJlAAcBAwAMoL4DANAAAgAAAAABgCAAAA==

**Comment by LagoLunatic** [comment]
The master sword chamber isn't a part of Tower of the Gods, it's part of Hyrule. To access Hyrule you only need all 8 Triforce shards, the pearls are unnecessary.
