### ISSUE TITLE
Hero Mode Adjustment

### ISSUE THREAD

**Issue by Crain-32** [LagoLunatic/wwrando#367]
Inspired by someone failing soup dupe in a call I was in, patching out Soup Dupe in Hero Mode could add another layer to the challenge the mode presents.

**Comment by wooferzfg** [comment]
I feel like patching out glitches (that are almost impossible to do accidentally) is a bit unnecessary because it's a single player game where it's easy to do a challenge run without using particular glitches.

**Comment by Crain-32** [comment]
You know I really need to remember that it's possible to just "not" do things.
Closing because you're 100% correct.
