### ISSUE TITLE
[Question] Tingle Tuner

### ISSUE THREAD

**Issue by RetroGamerAndre** [LagoLunatic/wwrando#37]
I was wondering if the tingle tuner can still be used. I tried to use it but it didn't detect the game boy advance sp. Is my cord messed up, or does it have to be an original Gameboy? Does the randomizer not support the tingle tuner? Hopefully I can figure out what went wrong. like I said, not sure if its the console, hand held, cord, or the randomizer itself. any help would be appreciated.

RetroGamerAndre

**Comment by LagoLunatic** [comment]
The randomizer doesn't modify the tingle tuner in anyway, it still works.

I've never used the tingle tuner in my life so I couldn't tell you what you're doing wrong.

Note though that the randomizer never requires you to use the tingle tuner, so even if you don't get it working you can still play.
