### ISSUE TITLE
unbeatable randomized run

### ISSUE THREAD

**Issue by Rarzhn** [LagoLunatic/wwrando#39]
I created a randomized game without glitches which seems to be unbeatable.
Permalink: MS4zLjAAUGFzdExlc3NTa2luAA8BwwEAAgEB

The Grappling Hook can be found at Rock Spire Isle which is blocked by a boulder.
The Bombs are hidden in Bomb Island which als requieres the Bombs.

Without the Grapplink Hook I'm not able to progress in Dragon Roose Cavern since I'm missing a Small Key. The only possible way in there would be to use the Deku Leaf in the big lava room to glide into the hole next to the lava fountain at the bottom of the room. To go even further the Grappling Hook is neccessary.

So I think this is run is unbeatable but maybe I'm missing something.

**Comment by JarheadHME** [comment]
You can get into bomb Island with the power bracelets. I don't know where it is in your permalink as I'm not at a pc right now, but that's my bet on what you need to do.

**Comment by LagoLunatic** [comment]
Power bracelets is sold by beedle for 20 rupees in this seed, so yes you can get those.
