### ISSUE TITLE
No logic

### ISSUE THREAD

**Issue by Callibean72** [LagoLunatic/wwrando#400]
There either need to be a setting to turn off logic or, like it should have been from the start, have it always be logic. I've had to many fucking seeds that I can't finish cause shit is locked behind something I can't get without another item I can't get because of where the items are put. Example, literally the seed I just tried to do: I need the bombs to get the hookshot but the hookshot it locked behind having to destroy the canons on a Lookout Platform which is only able to be done with the fucking bombs.
![image](https://github.com/user-attachments/assets/2730ba66-581d-4e88-8691-bc4a5e751b2b)

**Comment by LagoLunatic** [comment]
Logic is always enabled and all seeds are beatable, I'm not going to add a no logic mode.

For the section of the spoiler log you're looking at, you appear to be misreading it. Hookshot is locked behind Bombs, but Bombs are not locked behind Hookshot. They're locked behind Bait Bag, which allows you to get the big pig to dig up the black soil that contains the Bombs you need.

**Comment by Sage-of-Mirrors** [comment]
Is there a way to get the Private Oasis chest without hookshot? That seems to be what Callibean means - you need bombs or boomerang to get hookshot, but bait bag is locked behind the Private Oasis chest which AFAIK requires hookshot.

**Comment by wooferzfg** [comment]
> Is there a way to get the Private Oasis chest without hookshot? 

The Deku Leaf may be used instead.

I would suggest using the [tracker](https://www.wooferzfg.me/tww-rando-tracker/) to get familiar with requirements - you can hover over a location to see what items it needs and which ones you are missing.
