### ISSUE TITLE
Dragon Roost Cavern second small key

### ISSUE THREAD

**Issue by Addykins** [LagoLunatic/wwrando#401]
after the first room you enter a room with a bombable rock to your right. I blew up the rock entered the room that the rock was blocking the chest that was supposed to hold a key held a piece of heart and now I'm stuck.

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
