### ISSUE TITLE
Cannot generate ISO with random enemy colors selected

### ISSUE THREAD

**Issue by Insomninja42** [LagoLunatic/wwrando#403]
![IMG_3613](https://github.com/user-attachments/assets/26ce2590-aaf9-4daa-8e74-2bb148a58452)
When I try to generate an ISO with the random enemy colors setting it fails and gives me this message

**Comment by LagoLunatic** [comment]
According to your screenshot, you aren't using Wind Waker Randomizer, you're using betterww, which is an unofficial fork of the randomizer. Either report this as a bug in the betterww repo, or use the official randomizer which should work fine.

**Comment by Insomninja42** [comment]
My Bad, I wasn’t paying attention to the name of this repo, and I thought it was the BetterWW one, yeah I’ll go do that
