### ISSUE TITLE
[Suggestion] For 'Race Mode'/hints

### ISSUE THREAD

**Issue by Callibean72** [LagoLunatic/wwrando#405]
I have Race Mode on and all dungeons, I'm also using hints. A few times I've been told that a dungeon is foolish even though I need to go through it and fight the boss to get the triforce peace. It should be something different, it's super confusing sometimes.

**Comment by LagoLunatic** [comment]
This is the case in the next version/nightly build after race mode was reworked, as the bosses being required is now independent of the item they drop.
