### ISSUE TITLE
Game is in an infinite memory card loop

### ISSUE THREAD

**Issue by ifloat** [LagoLunatic/wwrando#42]
Before the main menu can even be accessed the game asks if I want to create a save file in slot A. Yes or no both result in the same. An error stating that there is no save file in slot A and asking if I want to create a play without saving. Yes and no both go back to asking me if i want to create a save file again. The original rom has no issues with save files.

**Comment by LagoLunatic** [comment]
What are you playing on? Dolphin, wii, gamecube?

**Comment by LagoLunatic** [comment]
Also, are you sure your memory card has free space on it? The randomizer uses a different memory card slot from the vanilla game, so if the card is full with the vanilla game on it that could explain why it works for vanilla but not randomizer.

**Comment by ifloat** [comment]
Using dolphin with a brand new empty memory card

**Comment by LagoLunatic** [comment]
What version of dolphin?

And can you take a screenshot of this config screen?
![dolphin mem card](https://user-images.githubusercontent.com/19174152/45310920-a8fde980-b4f5-11e8-8c51-bd19e37b4c59.png)

**Comment by ifloat** [comment]
<img width="576" alt="both" src="https://user-images.githubusercontent.com/18277486/45313750-bf0fa800-b4fd-11e8-952b-fb739d6a2508.png">
