### ISSUE TITLE
Cannons at the Eye Reefs missing

### ISSUE THREAD

**Issue by Zermox** [LagoLunatic/wwrando#44]
Original ISO is USA version
Permalink for settings: MS4zLjAAQ2hlcnJ5N1VwAP970wEAAgIB
Dolphin v. 5.0-5620, should probably update to latest version
Cannons at every eye reef are missing, no chest atop the according "eye" at any reef, tried a few seeds so that shouldn't be the issue. Also tried setting the eye reefs to not contain progression items to no effect.
![gzlr01-1](https://user-images.githubusercontent.com/21275436/45594319-77e64480-b94d-11e8-9217-6ff5808d2d3e.png)
I also used the wind waker falling glitch to swim underneath the island, but they weren't there either. I suppose that they just didn't load. FF and IoS cannons are loading fine. 
![gzlr01-2](https://user-images.githubusercontent.com/21275436/45594478-1f647680-b950-11e8-860f-6ad65bea110d.png)
![gzlr01-3](https://user-images.githubusercontent.com/21275436/45594497-7ff3b380-b950-11e8-8902-e944c8769662.png)
For now I'll just play without adding the eye reefs to the randomizer table, but it's better to report a bug than to ignore it.

**Comment by Zermox** [comment]
For now I'll just play without the Eye Reefs, but it's better to report an issue than to ignore it.

**Comment by LagoLunatic** [comment]
Not a bug, eye reef cannons and gunboats just don't appear until you've beaten phantom ganon in forsaken fortress. This is how it works in the vanilla game.

**Comment by Zermox** [comment]
Thanks for the info, sorry for the mispost.
