### ISSUE TITLE
Can't get Din's Pearl

### ISSUE THREAD

**Issue by Hotdogbum** [LagoLunatic/wwrando#45]
According to the spoiler log Din's Pearl is found in the Big Key Chest in the Tower of the Gods. Is there a way to get into the Tower of the Gods without it or is this a bug?

**Comment by LagoLunatic** [comment]
Upload your spoiler log.

**Comment by Hotdogbum** [comment]
Nevermind, I have realized I don't need to beat TotG to get to Hyrule.

**Comment by LagoLunatic** [comment]
True, but all items and locations should still be accessible.

Do you have random dungeon entrances turned on? If you do, you don't need the pearls to access TotG. The pearls would instead give you access to some other dungeon in place of TotG.

**Comment by Hotdogbum** [comment]
Yes, that was also true. There were no problems; I'm just a dingus.
