### ISSUE TITLE
Randomizer flagged as virus by Avast

### ISSUE THREAD

**Issue by Blackwolf291** [LagoLunatic/wwrando#46]
Avast finds the prebuilt Wind Waker Randomizer is flagged by avast for being infected with Win32:malware-gen. This applies to the 1.3 zip.

**Comment by LagoLunatic** [comment]
Disable your antivirus.

**Comment by Blackwolf291** [comment]
I realise this is likely a false positive, but any legit software should not trip antivirus software. I'm a programmer myself and would be more than happy to go in and fix the issue so that this program does not trigger antivirus warnings. i do not assume this program needs a malware-gen to operate correctly, and if it does include one intentionally, the antivirus is correct to prevent installation.

**Comment by LagoLunatic** [comment]
Avast and AVG just really don't like executables made by PyInstaller. It's not unique to the randomizer, lots of programs that use PyInstaller have had this issue. So it's not an issue in the randomizer's code.

I've already tried to fix the false positive several times. Even if something I do seems to fix it (e.g. using different versions of PyInstaller, compiling PyInstaller's binaries myself), a few days after releasing a new version it goes back to detecting it as malware.

If you think you know how to fix it then by all means give it a shot.

**Comment by Blackwolf291** [comment]
Looking into it more, it seems you're right and this is a well known issue with any applications made with the 32 bit pyinstaller, the 64 bit version does not have this issue, but as devs ofcourse we cannot assume everyone has a 32 bit machine, so, the best advice i can give is make a 64 bit version available, and state clearly on the download page that the 32 bit might give a false positive on avast and avg that is safe to ignore.

**Comment by LagoLunatic** [comment]
I tried using 64 bit python and it does seem to fix the issue, it went from 6/66 programs detecting the 32 bit randomizer as a false positive down to 0/67 for the 64 bit one.

Hopefully it stays that way and doesn't revert to being detected as malware yet again in a few days. If that doesn't happen I'll include a 64 bit build in the next release.
