### ISSUE TITLE
Need bombs to progress

### ISSUE THREAD

**Issue by jamesdean20** [LagoLunatic/wwrando#47]
Wind Waker Randomizer Version 1.3.0
Permalink: MS4zLjAAUmVkTmVydm91c0dhdGhlcmluZwD//+MBAAIAAQ==
Seed: RedNervousGathering

To get bombs I need to destroy cannons at five-star isles. I tried going around and getting the triforce shards to go to hyrule but one of the shards is in the 5 eye reef chest which I need bombs to get. I don't see a way around this at the moment, but I'm continuing to try to find a way. 

I tried finding some creative ways to destroy cannons, but nothing has worked so far.

**Comment by LagoLunatic** [comment]
Two hits from the boomerang destroys a cannon.
