### ISSUE TITLE
Stuck in arena.

### ISSUE THREAD

**Issue by Shen548** [LagoLunatic/wwrando#5]
If you dont have the hookshot by the time you get to the mini boss fight to save medli on dragon roost isle. You will get stuck in the arena once the gate closes. Seed: (SixAlikeTrouble) Saving and restarting the file fixes.
![gzlr01-3](https://user-images.githubusercontent.com/35537673/42810412-174ac144-8975-11e8-8ef7-37e83d8c2e89.png)

**Comment by LagoLunatic** [comment]
There's no way for the randomizer to avoid this. There are a number of locations you can get trapped like this, just save and reload.
