### ISSUE TITLE
[Suggestion] Cosmetic Swords

### ISSUE THREAD

**Issue by Sparky7198** [LagoLunatic/wwrando#51]
Wouldn't it be neat if you could set The Diferent Master Sword Levels to be diferent sword's? aside from the Hero sword's. i mean we could have the Phantom And Lokomo Swords in the game. and their models do exist in Hyrule warriors.

**Comment by LagoLunatic** [comment]
The randomizer can already load in any custom models inside Link.arc, which includes swords. It's just that no custom models have done this yet.

But making different master sword levels entirely different models is impossible.
