### ISSUE TITLE
Stuck in Dragon Roost Cavern

### ISSUE THREAD

**Issue by Fargarkle** [LagoLunatic/wwrando#54]
Hi, I was just wanting to let someone know I encountered a bug with the randomizer. I am currently in Dragon Roost Cavern and have used up all of my small keys and can no longer continue the dungeon. The first two small keys I had to use to get to the door that is right next to the bird's nest. The next small key I can get is after that locked door but can't cause I used them all to get to that door. Here is my spoiler log and my Dolphin version is 5.0-8909. Thanks.
[WW Random FrivolousProsperousDelivery - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/2492298/WW.Random.FrivolousProsperousDelivery.-.Spoiler.Log.txt)

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
