### ISSUE TITLE
[Suggestion] Sail speed and wind change

### ISSUE THREAD

**Issue by thegreatdeox** [LagoLunatic/wwrando#58]
Would it be possible to detach sail speed and wind change from each other in the randomizer?

I like having the wind change direction as I turn but the sail makes me go too quickly to enjoy the sailing around aspect and bits like the boating course are far too irritating now

**Comment by LagoLunatic** [comment]
FYI you can stop the boat instantly by pulling out the wind waker when sailing.

The boating course is indeed borderline impossible, but it doesn't give anything besides a couple rupees anyway.
