### ISSUE TITLE
Softlock

### ISSUE THREAD

**Issue by asup759** [LagoLunatic/wwrando#59]
MS40LjEAY2FwcHljb29sAAcNwgMAAgAB
according to spoiler log, bombs are found by digging in outset (bait required), bait bag is found in pawprint isle "scale the wall" (grappling hook required), grappling hook found on 5-star isles platform by breaking the cannons (bombs required).

**Comment by JarheadHME** [comment]
You can destroy the canons on platforms with the boomerang.

**Comment by asup759** [comment]
that's crazy, didn't know that. thanks
