### ISSUE TITLE
trouble randomizing

### ISSUE THREAD

**Issue by zentainmh** [LagoLunatic/wwrando#6]
i am kinda bad at this stuff but i have randomized my ww iso and everytime i open it in dolphin it is the regular ww iso, i already downloaded the newest version of dolphin and nothing, also the cant join the discord, pls help

**Comment by LagoLunatic** [comment]
The randomizer doesn't modify your vanilla Wind Waker ISO. It spits out a randomized ISO in the output folder you specified. You need to launch the randomized ISO, not the vanilla one.

**Comment by zentainmh** [comment]
hahaha i am so bad thank you so much, got it working
