### ISSUE TITLE
[Bug] Missing Key in DRC

### ISSUE THREAD

**Issue by IncredulousPasserby** [LagoLunatic/wwrando#61]
Permalink to the game: MS40LjEATmV3TWF0dXJlRmxhbWUAl8mDAwACAQE=
Issue: I believe one of the DRC keys got badly randomized. I don't have Key Lunacy on, but after the first three chests I should have two keys, as I can't progress past that point without a second key. The second key is behind the second locked door, in the chest across the lava pit, according to the spoiler log. Damn shame, too, it was a fun game so far.

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
