### ISSUE TITLE
Can't get Grappling Hook

### ISSUE THREAD

**Issue by InfinityandChaos** [LagoLunatic/wwrando#62]
Permalink: MS40LjEAQXdlc29tZVdvcnRoeUdvc3NhY2sA////AwADAAE=
Seed: AwesomeWorthyGossack

Ankle - Reward for All Tingle Statues:               Grappling Hook
Letter from Baito:                                   Tingle Tuner

I have all 5 Statues but Ankle is not there. If I need the tingle tuner, I can't get that as that is from Baito's letter and it has yet to show up after many days. How long does it take? I got the letter from his mom but not from him. I sent his letter to his mom before completing the mail sorting minigame with him. Could doing those in that order have broken it or is there something else I have to do?

**Comment by JarheadHME** [comment]
I think the randomizer actually has him misnamed. Ankle is the blue tingle guy yeah? The guy you talk to for the reward is the pink one spinning the tower.

**Comment by InfinityandChaos** [comment]
My mistake that is ankle. Thank you!
