### ISSUE TITLE
Possible Softlock

### ISSUE THREAD

**Issue by innateconversations** [LagoLunatic/wwrando#64]
I had acquired the Hero's Bow and the Command Melody early on, and I found my way into the Tower of the Gods (randomized dungeon entrances). I was making my way through the dungeon when I came to the part where you have to guide the statues to that center room, where you normally learn the Command Melody.

The second statue, you would normally set on a panel that unlocks the door to the miniboss (where you would normally get the bow). Then you would use the bow on the eye to make the platforms move so that you can carry the statue across the gap.

Silly me just shot the eye and carried the statue over to the center room without entering the miniboss.
I can't seem to find a way to find anything to set on the panel as the monsters across the room become enemies. I looked in the spoiler log and found that the miniboss carries the Mirror Shield.

So, my question is, is there something I can set on that panel to get to the miniboss?
Or, is the Mirror Shield required for the Earth Temple, or for the final segment of the Ganondorf battle?

If this is a softlock, I would make the suggestion to make it so that the Armos don't come alive so that one could carry them over to set on the panel.

**Comment by LagoLunatic** [comment]
Can't softlock there, one of the two armos in that room never comes alive, so you can use that one on the switch.
