### ISSUE TITLE
Got Stuck in Pirate Ship

### ISSUE THREAD

**Issue by Grip555** [LagoLunatic/wwrando#66]
I started a game, went to the pirate ship and I opened the chest, then the door got locked and I got stuck!

Plus I hadn't saved yet and now I want options that let you start with some treasure boxes unlocked by default. :/

**Comment by LagoLunatic** [comment]
Not a bug. You can just save the game while stuck in that room, then reload your save and you'll be outside. There are several places in the game where you may need to do this, such as every miniboss.
