### ISSUE TITLE
[Suggestion] Hero Mode

### ISSUE THREAD

**Issue by Sparky7198** [LagoLunatic/wwrando#67]
Even if the Randomizer could potentially not give you Heart Pieces/Containers for a good while i feel like the game is still too Easy so having the HD's Hero Mode on the Gamecube version would be a nice touch. or even an even Harder mode with OHKO or four times the damage

**Comment by P3rf3ctXZer0** [comment]
After having a discussion in ZOotr discord I determined that for Zelda games to be truly hard without being OHKO is x8 and x12 damages. That way later bosses are all but OHKO and Early game is a real threat

**Comment by FatBoySlim2000** [comment]
Maybe when enemies hurt you (including bosses) they regain health. Or double the health of enemies.

**Comment by TheGameCreator13** [comment]
This is easily achieved with AR codes

In fact here's the one I'm using made by Ralf

> $Link Takes Damage Multiplier [Ralf]
> 04003B80 8061000C
> 04003B84 74648000
> 04003B88 41820008
> 04003B8C 1C6300xx
> 04003B90 481EDB10
> 041F169C 4BE124E4

Just replace "xx" with the value you want it multiplied by (04 = x4 damage | 01 = Default Damage (x1))

To add it to your game Right-click your game and go to
Properties>Game Config>Editor>User Config
And paste the code under **[ActionReplay]** and it'll popup in the cheats menu

Would be nice as an actual option of course for user convenience but for now this method works just fine.

To me x4 damage makes a good Harder Difficulty Mode with Heart Drops on but if you want Hearts to not drop like Wind Waker HD's Hero Mode then look up an AR code for that as well. Make sure it works specifically with the USA version of Wind Waker though
