### ISSUE TITLE
Light Arrows Healing Bosses?

### ISSUE THREAD

**Issue by Sparky7198** [LagoLunatic/wwrando#68]
I had the Hero's Charm and wanted to test if Light arrows did anything aside from the Jalhalla Fight. Specificialy Gohma,Turns out it actually Healed her and her Health Bar even passed the Limit of it(The White bar around it),didn't test futher to see if the HP Bar would go off screen,not sure if it has the Same Results for Molgera and Kalle Demos

**Comment by LagoLunatic** [comment]
Yes, the original developers specifically coded Gohma to be healed by light arrows. No idea why. Pretty sure they don't do anything to other bosses besides Gohma and Jalhalla.
