### ISSUE TITLE
[Suggestion]  Randomizing Loading Zones

### ISSUE THREAD

**Issue by cabatsha** [LagoLunatic/wwrando#69]
Is it possible to randomize the loading zones so that each door/ warp pot/ cave leads to a different place? It looks like somebody has created this here,  https://github.com/CryZe/WindWakerBetaQuest but I really don't understand the instructions. Is it possible to add something like this with your program, which has a user-friendly interface?

**Comment by LagoLunatic** [comment]
I'm not adding an option to randomize every single loading zone. I'm planning to add one to randomize secret cave entrances, but not things like houses, mini bosses, etc since that wouldn't be fun.
