### ISSUE TITLE
Unwinnable setup

### ISSUE THREAD

**Issue by McBehrer** [LagoLunatic/wwrando#70]
I am playing through (seed MusicalAfraidDog) and I think it's unwinnable.

I need the Command Melody, which is in a sunken chest at Needle Rock Isle.
I get the Chart for delivering Maggie's Letter.
I need the Delivery Bag to do that.
The Delivery Bag is in a sunken chest at Northern Fairy Isle.
The Chart for that is in the Wind Temple.
Which I can't get to without the Command Melody.

So the Command Melody is locked BEHIND THE COMMAND MELODY

**Comment by LagoLunatic** [comment]
You're most likely misreading something. Upload the spoiler log.

**Comment by McBehrer** [comment]
... uh huh. Let me try that.

**Comment by McBehrer** [comment]
Ugh. Of COURSE that was it. thanks!
