### ISSUE TITLE
Need item X to get to Y and vice versa

### ISSUE THREAD

**Issue by GonthorianDX** [LagoLunatic/wwrando#71]
So I got myself a seed, explored everything til I got stuck, read up in my spoiler log what I missed, low and behold two platform chests holding two progresssion items.

I was looking for bombs and the grappling hook as those are the two most significant items. This is what I found:

>Stone Watcher Island:
      Lookout Platform - Destroy the Cannons:              Grappling Hook
Eastern Triangle Island:
      Sunken Treasure:                                     Bombs

So to destroy the cannons, the only method that I am aware of are Bombs, but those are on the sea floor which I need the Grappling Hook for to reach, I can't get the Grappling Hook because I need Bombs to blow up the cannons.

Is this a bug or is there some weird method that I do not know about?

Wind Waker Randomizer Version 1.4.1
Permalink: MS40LjEAU2VlZHlGaWRkbGluZ1ByYXllcgDf/fsDAAIAAQ==
Seed: SeedyFiddlingPrayer
Options selected:
  progression_dungeons, progression_great_fairies, progression_puzzle_secret_caves, progression_combat_secret_caves, progression_short_sidequests, progression_spoils_trading, progression_minigames, progression_free_gifts, progression_platforms_rafts, progression_submarines, progression_eye_reef_chests, progression_big_octos_gunboats, progression_triforce_charts, progression_treasure_charts, progression_expensive_purchases, progression_misc, keylunacy, randomize_dungeon_entrances, randomize_charts, randomize_starting_island, swift_sail, instant_text_boxes, reveal_full_sea_chart, num_starting_triforce_shards: 0, generate_spoiler_log, sword_mode: Start with Sword, skip_rematch_bosses, invert_camera_x_axis, custom_player_model: Link, custom_colors: OrderedDict([('Hair', [147, 136, 9]), ('Skin', [246, 233, 215]), ('Shirt', [120, 0, 180]), ('Undershirt', [85, 0, 127]), ('Pants', [0, 0, 0])])

**Comment by LagoLunatic** [comment]
>So to destroy the cannons, the only method that I am aware of are Bombs

2 hits from the boomerang destroys cannons
