### ISSUE TITLE
Dragon Roost Cavern

### ISSUE THREAD

**Issue by Morzli** [LagoLunatic/wwrando#72]
Got a triforce piece instead of a key in the dungeon. I can’t move forward...

**Comment by Sparky7198** [comment]
Do you have Ice Arrows or The Deku leaf?

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl

**Comment by LagoLunatic** [comment]
In the vanilla game, you have to use the tingle bomb. In the randomizer, a regular bomb works.

**Comment by Morzli** [comment]
Oh okay. Thanks. Appreciate the help. I don’t have the bombs yet. I assume it’s not possible for them to be located further into dragon Roost Cavern? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LagoLunatic** [comment]
Correct, since if they were the seed would be unbeatable, which the randomizer prevents.

**Comment by Morzli** [comment]
Gotcha, thanks for the help!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
