### ISSUE TITLE
Award For Collecting Tingle Statues

### ISSUE THREAD

**Issue by Morzli** [LagoLunatic/wwrando#73]
I collected four of the tingle statues and then got the $500 reward in the mail. I got the fifth statue some time later. Is that supposed to happen?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LagoLunatic** [comment]
The 500 rupee is a randomized item. It can appear anywhere, at any time, regardless of how many tingle statues you own - like almost every other item in the randomizer.

If you want the reward for collecting all 5 tingle statues, talk to ankle on tingle island.
