### ISSUE TITLE
[Suggestion] More Options

### ISSUE THREAD

**Issue by Grip555** [LagoLunatic/wwrando#74]
I want more options, for example:

Specify which minigames and side missions are ticked off, like having Korok and Baito unticked, but have everything else on.

Disable randomization for certain dungeons or even specific boxes in dungeons.

Have items that increase the amount of bombs, arrows ect... you can hold be important.

Have different ways to end the game, like for ALttP randomizes, like getting all 3 orbs/Get all Triforce pieces/find all sunken treasures ect...

Always have the wind blow you towards the right direction, to make getting to Forbidden Woods less annoying.

**Comment by Sparky7198** [comment]
You can't really make the Wind always blow in your Direction in Terms of gameplay. there are plenty of quest's that require you to have the wind at a certain point without you gliding somewhere with the Deku Leaf

**Comment by LagoLunatic** [comment]
Alternate ending conditions might be interesting. Not sure how to code that though.

I don't want the other things.
