### ISSUE TITLE
Not working in Dolphin (black screen)

### ISSUE THREAD

**Issue by 03bgood** [LagoLunatic/wwrando#75]
It works fine on my Wii U via Nintendont, but on Dolphin, I get this error:

"invalid write to 0x01234567 PC =80006d64"

BTW, I'm using Dolphin 5.0-540.

Even tried the latest dev build, 5.0-9186, same thing happens. I don't get the error message in the 9186 build and I also don't get it in the 540 build, if I disable "Use Panic Handlers". It still shows a black screen, regardless of the situation or which version of Dolphin I use. Ironically, the regular vanilla ISO of the game seems to run fine. So why aren't any of the randomized ISOs working?

**Comment by Grip555** [comment]
Did you overwrite all old files for 5.0-9186? Maybe you need a clean install.

**Comment by LagoLunatic** [comment]
You shouldn't get the issue on version 5.0-9186. Most likely you simply accidentally ran 5.0-540 even after downloading 5.0-9186. Go to Help -> About in dolphin and make sure the version number there says 5.0-9186.

**Comment by 03bgood** [comment]
Have no idea how to update Dolphin. When I try to extract the 9186 build to the same folder, I get an error saying "The application failed to start because no QT platform plugin could be initialized."

**Comment by LagoLunatic** [comment]
Maybe you didn't extract it, and are trying to run the executable from within the compressed folder. Or maybe it didn't extract correctly. I recommend using the latest version of 7-zip to extract it: https://www.7-zip.org/

Or maybe you have a really old operating system that dolphin doesn't support anymore like windows XP.

In any case, not an issue with the randomizer.

**Comment by 03bgood** [comment]
Finally got the 9186 build to work, but the ISO (Randomizers) still show a black screen!

**Comment by LagoLunatic** [comment]
Does vanilla wind waker run in build 9186?

**Comment by 03bgood** [comment]
Yes, but the screen is black with the sound still playing.

**Comment by LagoLunatic** [comment]
You have the video backend set to null. Go to graphics config and change Backend to OpenGL or something.

**Comment by JarheadHME** [comment]
Graphics > Backend, change it to anything that isn't Null (usually either direct3d or OpenGL)

**Comment by 03bgood** [comment]
OpenGL is not working but Direct3D does.

**Comment by JarheadHME** [comment]
...So then use Direct3D? He said "OpenGL *or something*". Just use Direct3D.

**Comment by 03bgood** [comment]
Direct3D seems to run the rando fine, as well as the other ISOs, but OpenGL is no longer displaying video!

**Comment by LagoLunatic** [comment]
Yes what you should use depends on your computer. OpenGL works best for my computer but if you need to use something else then do so.

**Comment by 03bgood** [comment]
OpenGL worked fine on 5.0-540, but not the new build.

**Comment by LagoLunatic** [comment]
Then I would assume one of the 8646 changes made to dolphin between those versions broken opengl for your computer. This isn't related to the randomizer so I'm locking this thread.
