### ISSUE TITLE
Sometimes a rendering glitch causes the overworld screen to go blurry (Nintendont)

### ISSUE THREAD

**Issue by 03bgood** [LagoLunatic/wwrando#77]
This doesn't happen much, but when it does; the game freezes for about 2 seconds and the screen becomes blurry, for some reason. The only way to fix this, is to reset the Wii U console and launch the game, again. Saving and quitting doesn't seem to fix it and it only seems to effect the in game graphics and nothing else. I noticed that this only happens while sailing. It doesn't happen when you're on an island, as far as I know.

**Comment by Sparky7198** [comment]
I never Gotten a Blurry Screen myself, you using the Latest Version of Nintendont?

**Comment by wooferzfg** [comment]
This is Light Glitch, which exists in the vanilla game.
