### ISSUE TITLE
Can't Beat Dragon Roost Cavern

### ISSUE THREAD

**Issue by Grip555** [LagoLunatic/wwrando#78]
I can get up to the bird nest, but since the door after that requires a key and I already opened all the chests I could find, I'm stuck being unable to complete the dungeon.

**Comment by LagoLunatic** [comment]
The next small key you need is in the big key chest or the tingle chest near there.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl
