### ISSUE TITLE
[Suggestion] Linux Version

### ISSUE THREAD

**Issue by L094N-4** [LagoLunatic/wwrando#82]
Is a Linux version available? If not, can you make one? (Yes, I know Wine is a thing, but it often runs poorly when dealing with large files)

**Comment by LagoLunatic** [comment]
It should be possible to run the randomizer from source on linux, I believe several people have done so before. Check the bottom of the readme for instructions (the instructions are for windows/mac but I assume they're pretty much the same on linux).

From what people have said, Wine can't run the randomizer anymore.

Compiling a prebuilt executable for linux would need to be done on linux itself, but I haven't managed to figure out how to get a linux VM working on my computer yet, so don't hold your breath for this.

**Comment by P3rf3ctXZer0** [comment]
@L094N-4 just go grab windows 10 virtual machine - install os - and run randomizer and use linux dolphin. Worked for me.

**Comment by isghj5** [comment]
This didn't work:
python3 -m pip install -r requirements.txt --user
but if you use cat it does
python3 -m pip install $(cat requirements.txt) --user

For some reason the randomzier crashes if you try to run it as a regular user (seg fault) but runs fine with sudo (1.5.1 release running on xubuntu 18.10)
