### ISSUE TITLE
Dragon Tingle Statue Error

### ISSUE THREAD

**Issue by sparksac** [LagoLunatic/wwrando#83]
I am getting this error only when I try to randomize the combat secret cave, any ideas.
![error](https://user-images.githubusercontent.com/37055519/49768302-df403600-fca9-11e8-8618-398fee205dd1.PNG)

**Comment by LagoLunatic** [comment]
Yeah this bug is fixed for the next version. It happens when a tingle statue gets put in savage labyrinth, so you can avoid it by just using a different seed.

**Comment by sparksac** [comment]
Thanks!
