### ISSUE TITLE
Suggestion - Start with grappling hook

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LagoLunatic/wwrando#88]
So this game is huge and to be honest not being to get sunken treasure - is the worst - is it possible to add an option to start a seed with the grappling hook?

**Comment by Grip555** [comment]
Yeah, options to start with specific weapons would be handy.

**Comment by P3rf3ctXZer0** [comment]
It would make speedrunning way more viable.

**Comment by LagoLunatic** [comment]
You can disable the options to put progress items in the sunken treasure. If you do that not starting with grappling hook is not nearly as big a deal.

**Comment by P3rf3ctXZer0** [comment]
Okay well I want to be able to hunt sunken treasure then what settings do I set so I start with grappling hook? I wasn't look for ways to shrink item pool I was looking for a way to start with a grappling hook. @LagoLunatic
