### ISSUE TITLE
[Bug] Chest not spawning on enemy clear

### ISSUE THREAD

**Issue by Tormyst** [LagoLunatic/wwrando#89]
Wind Waker Randomizer Version 1.4.1
Permalink: MS40LjEARXZpbE1hcnJpZWRMYXNzAP//+wMAAwEB
Seed: EvilMarriedLass

When attempting to complete the required chest: Kill All Enemies in Tall Basement Room in wind temple
The chest will not spawn.  

I am not sure if this is an issue with the Progressive Sword in the chest or something about the seed or even something with using light arrows.

My run got me to go me to collect 286 items, and as such, this was not a great thing to happen at the end of the run.  I had collected all key items except for 1 piece of heart and the telescope.  I was using the master sword powered up once, bombs and light arrows during the battle the first time.  Just using the blade in future attempts did not help. 

I feel that there are many places in the game, usually caves where chests that should spawn do not.  On the second attempt, the chest usually spawns.  However for this chest specifically, the enemies in the room respawn and defeating all of them will not make the chest appear.

**Comment by JarheadHME** [comment]
That room is really weird memory-wise (or so I've heard a lot from people who speedrun the game and such) and generally has that issue fairly frequently even in Vanilla. Usually exiting and reentering the room will respawn any enemies that didn't die properly, but it sounds like you've tried that already? Worth mentioning just in case that it might include some of the bokoblin behind the heads.

**Comment by Tormyst** [comment]
It defenetly seems like a game thing.  I'm not a speedruner and this was my first time really moving fast through the game.  I will give it a few more tries and update if I can get it to spawn.

**Comment by Tormyst** [comment]
Seems like it was bad luck.  I tried it again, and it seemed to work.
