### ISSUE TITLE
Swordless mode error?

### ISSUE THREAD

**Issue by Bufosmixes** [LagoLunatic/wwrando#90]
So, I did swordless. Does this mean you will literally never get a sword (I got all the way up to the final fight, and then for the first time I actually needed the sword) and I did literally everything (0 remaining in tracker) so I pretty much never got a sword. Spoiler log does not have a location to find sword. So does swordless mean you don't get one? Or is this a bug?

**Comment by wooferzfg** [comment]
Swordless means you never get a sword. Randomized Sword means you start without a sword but you'll find one in a random location.
