### ISSUE TITLE
Suggestion - Random music, island locations?

### ISSUE THREAD

**Issue by Bufosmixes** [LagoLunatic/wwrando#91]
Is it possible to have randomized music? It can be quite humorous, I saw it in an OoT randomizer. Also, I think it would be quite neat to have randomized islands. Islands are not where they are supposed to be, which I think would keep things fresh. Are these and other settings possible?

**Comment by FatBoySlim2000** [comment]
Randomizing island locations would be sweet, making any seed more crazy.

**Comment by LagoLunatic** [comment]
The BGM randomizer option I added in 1.6.0 but it's still buggy and incomplete and I doubt I'll ever feel like figuring out how to fix it. If someone else wants to do so, go ahead.
The option can be accessed by opening settings.txt in a text editor and changing `randomize_bgm: false` to `randomize_bgm: true`.

Random island locations isn't happening ever.
