### ISSUE TITLE
Is it Possible to Trigger the Makar Rescue cutscene?

### ISSUE THREAD

**Issue by Nadodan** [LagoLunatic/wwrando#94]
Hello I was lucky enough to get all the items I needed to reach and defeat the Forbidden Woods boss. I expected to get 2 items from this 1.Would be the replacement for the heart container the boss would drop and 2.Would be the replacement item for Farore's Pearl. I only received the first of these items however and talking to the Deku Tree has him saying I need to collect the leaf. I had the leaf in my inventory but didn't grab the replacement item. So I proceeded to grab the replacement item and then go through the Forbidden Woods Warp again. However, this still didn't lead to me receiving an item.

Were these methods of obtaining items completely removed? If not where can I find them? I already experienced something similar when I went to the Great Jaboon's cave and found nothing. If these items were moved to a new chest somewhere like the Great Fairy at Mother and Child island's item. Please let me know the new holding place.

**Comment by JarheadHME** [comment]
They were removed. The only two cutscene items (I believe?) that you can get are mother and child, and the drc miniboss chest. All other cutscene spots are empty.
