### ISSUE TITLE
Stuck...can't complete any dungeon

### ISSUE THREAD

**Issue by iFaxity** [LagoLunatic/wwrando#95]
[WW Random AliveFierceBisht - Spoiler Log.txt](https://github.com/LagoLunatic/wwrando/files/2760357/WW.Random.AliveFierceBisht.-.Spoiler.Log.txt)

As the title says i'm stuck and cant complete any dungeon because most the basic progressive items are locked in dungeons i cant access without glitches/skipping .
The spoiler log is attached to the issue for more details.

**Comment by LagoLunatic** [comment]
The next small key you need in DRC is in the big key chest.

You can reach it by using either deku leaf: https://imgur.com/jOEq6mx
Or ice arrows: https://imgur.com/R0cYujl

**Comment by JarheadHME** [comment]
Uh, not sure what you mean. Near the top of the spoiler log is a playthrough section, and from my following along with it then you should be able to beat the game no problem. Most of the items you need aren't in dungeons anyways.

**Comment by iFaxity** [comment]
However i don't have the grappeling hook so the door is closed. 
And ice arrows are in a dungeon i cant complete either.

**Comment by iFaxity** [comment]
Ok thanks.
