### ISSUE TITLE
[Suggestion] Select Gear you Start with in Logic

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LagoLunatic/wwrando#98]
One thing I am sort of confused about is why we cannot choose gear we start with? Yes this does fall back to my first request but maybe someplayer would rather start with bombs or the bow. If it is possible can you allow us to choose the gear the seed spawns with?

**Comment by Grip555** [comment]
Yeah, I'd like to start with a better wallet, since it could be a huge pain if you get the wallets late in the game, meaning Triforce Charts and more expensive items need to be got by grinding instead of via playing the game.
