### ISSUE TITLE
[Suggestion] Multiworld Support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LagoLunatic/wwrando#99]
So I have been getting really into ZOotr randomizer multiworld and I have had friends ask - is there a way to make a wind waker varient? Maybe ask dolphin team if they could help add support - I happen to know that they are pretty open to different types if changes. Also they already have network support so maybe they just add specific hooks for wind waker randomized.

**Comment by LagoLunatic** [comment]
I have no interest in this nor do I know anything at all about networking. If someone else wants to they can try to implement it but I imagine dolphin not having lua scripting support will make it pretty difficult.
